[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

# BSS setup
**.numHosts = 2

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[0].mobility.initialY = 200m
**.host[1].mobility.initialX = 270m
**.host[1].mobility.initialY = 200m

# UDP traffic setup from server to host[0]
*.server.numApps = 1
*.server.app[0].typename = "UdpBasicApp"
*.server.app[0].destAddresses = "host[0]"
*.server.app[0].destPort = 5000
*.server.app[0].messageLength = 1200B
*.server.app[0].sendInterval = 0.3ms
*.server.app[0].startTime = 0.2s
*.server.app[0].stopTime = 0.9s

[Config Base]
abstract = true
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].bitrate = 65Mbps

[Config Ht20MHz]
description = "HT 802.11n 20 MHz channel operation in 2.4 GHz"
extends = Base
**.opMode = "n(mixed-2.4Ghz)"
**.bandName = "2.4 GHz (20 MHz)"

[Config Ht40MHz]
description = "HT 802.11n 40 MHz channel operation in 2.4 GHz"
extends = Base
**.opMode = "n(mixed-2.4Ghz)"
**.bandName = "2.4 GHz (40 MHz)"

[Config Ht40MHzSecondaryAbove]
description = "HT 802.11n 40 MHz with secondary channel above primary"
extends = Base
**.opMode = "n(mixed-2.4Ghz)"
**.bandName = "2.4 GHz (40 MHz)"
**.wlan[*].radio.channelWidth = 40MHz

[Config Ht40MHzSecondaryBelow]
description = "HT 802.11n 40 MHz with secondary channel below primary"
extends = Base
**.opMode = "n(mixed-2.4Ghz)"
**.bandName = "2.4 GHz (40 MHz)"
**.wlan[*].radio.channelWidth = 40MHz
