[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 2s

# BSS setup
**.opMode = "n(mixed-2.4Ghz)"
**.numHosts = 2

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[0].mobility.initialY = 200m
**.host[1].mobility.initialX = 270m
**.host[1].mobility.initialY = 200m

# Enable mobility on host[0] to change distance over time
*.host[0].mobility.typename = "LinearMobility"
*.host[0].mobility.speed = 15mps
*.host[0].mobility.angle = 0deg

# UDP traffic setup from server to host[0]
*.server.numApps = 1
*.server.app[0].typename = "UdpBasicApp"
*.server.app[0].destAddresses = "host[0]"
*.server.app[0].destPort = 5000
*.server.app[0].messageLength = 1000B
*.server.app[0].sendInterval = 1ms
*.server.app[0].startTime = 0.2s
*.server.app[0].stopTime = 1.9s

*.host[0].numApps = 1
*.host[0].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000


[Config FixedMcs7]
description = "HT 802.11n fixed MCS 7 rate without dynamic rate adaptation"
**.wlan[*].bitrate = 65Mbps
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].radio.transmitter.mcs = 7

[Config HtMinstrelAdaptation]
description = "HT 802.11n dynamic Minstrel rate adaptation algorithm"
**.wlan[*].bitrate = 65Mbps
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].mac.hcf.rateControl.typename = "Ieee80211HtMinstrel"
