[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

**.wlan[*].classifier.typename = "ExampleQosClassifier"
**.wlan[*].mac.qosStation = true

# BSS setup in 5 GHz
**.opMode = "ac"
**.numHosts = 3

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.arp.typename = "GlobalArp"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[*].mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[1].mobility.initialX = 270m
**.host[2].mobility.initialX = 280m

# High-throughput UDP traffic setup
*.server.numApps = 3
*.server.app[0..2].typename = "UdpBasicApp"
*.server.app[0..2].packetName = "UdpBasicApp" + string(index)
*.server.app[0..2].destAddresses = "host[" + string(index) + "]"
*.server.app[0..2].messageLength = 1400B
*.server.app[0..2].sendInterval = 0.005ms
*.server.app[0..2].startTime = 0.2s
*.server.app[0..2].stopTime = 0.5s
*.server.app[*].destPort = 80

*.host[*].numApps = 1
*.host[*].app[0].typename = "UdpSink"
*.host[*].app[0].localPort = 80


[Config Base]
abstract = true
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.bandName = "5 GHz (80 MHz)"
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].mac.hcf.rateSelection.mgmtFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.controlFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseAckFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseBlockAckFrameBitrate = 6Mbps
**.wlan[*].radio.receiver.bandwidth = 80MHz
**.maxBlockAckPolicyFrameLength = 1500B
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = "VhtMpduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.maxAmpduLengthExponent = 3


[Config SingleStreamVht]
description = "VHT 1x1 Single Spatial Stream (MCS 9 in 80 MHz, 433.3 Mbps)"
extends = Base
**.wlan[*].radio.antenna.numAntennas = 1
**.wlan[*].mib.vhtShortGi80 = true
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 433.3Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1
**.wlan[*].mib.vhtMaxMcs = 9
**.wlan[*].mib.vhtMaxNss = 1

[Config FourStreamVht]
description = "VHT 4x4 Quad Spatial Streams (MCS 9 in 80 MHz, 1.733 Gbps)"
extends = Base
**.wlan[*].radio.antenna.numAntennas = 4
**.wlan[*].mib.vhtShortGi80 = true
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 1733.3Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 4
**.wlan[*].mib.vhtMaxMcs = 9
**.wlan[*].mib.vhtMaxNss = 4

[Config EightStreamVht]
description = "VHT 8x8 Eight Spatial Streams (MCS 9 in 80 MHz, 3.466 Gbps)"
extends = Base
**.wlan[*].radio.antenna.numAntennas = 8
**.wlan[*].mib.vhtShortGi80 = true
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 3466.7Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 8
**.wlan[*].mib.vhtMaxMcs = 9
**.wlan[*].mib.vhtMaxNss = 8
