[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

**.wlan[*].classifier.typename = "ExampleQosClassifier"
**.wlan[*].mac.qosStation = true

# BSS setup in 5 GHz
**.opMode = "ac"
**.numHosts = 3

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[*].mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[1].mobility.initialX = 270m
**.host[2].mobility.initialX = 280m

# High-throughput UDP traffic setup
*.server.numApps = 3
*.server.app[0..2].typename = "UdpBasicApp"
*.server.app[0..2].packetName = "UdpBasicApp" + string(index)
*.server.app[0..2].destAddresses = "host[" + string(index) + "]"
*.server.app[0..2].messageLength = 1400B
*.server.app[0..2].sendInterval = 0.05ms
*.server.app[0..2].startTime = 0.2s
*.server.app[0..2].stopTime = 0.9s
*.server.app[0].destPort = 5000
*.server.app[1].destPort = 5001
*.server.app[2].destPort = 5002

*.host[*].numApps = 1
*.host[*].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000
*.host[1].app[0].localPort = 5001
*.host[2].app[0].localPort = 5002


[Config Base]
abstract = true
**.wlan[*].bitrate = 65Mbps
**.wlan[*].mac.hcf.isBlockAckSupported = true

[Config StandardHtAmpduLimit]
description = "Standard 802.11n HT A-MPDU maximum length limit (65535 bytes)"
extends = Base
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = "VhtMpduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.maxAmpduLengthExponent = 3

[Config ExtendedVhtAmpduLimit]
description = "Extended 802.11ac VHT A-MPDU maximum length limit (1048575 bytes)"
extends = Base
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = "VhtMpduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.maxAmpduLengthExponent = 7
