[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 2s

**.wlan[*].classifier.typename = "ExampleQosClassifier"
**.wlan[*].mac.qosStation = true

# BSS setup in 5 GHz
**.opMode = "ac"
**.numHosts = 3

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.arp.typename = "GlobalArp"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[*].mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[1].mobility.initialX = 270m
**.host[2].mobility.initialX = 280m

# Enable mobility on host[0]
*.host[0].mobility.typename = "LinearMobility"
*.host[0].mobility.speed = 15mps
*.host[0].mobility.angle = 0deg

# Identical UDP traffic setup from server to all hosts
*.server.numApps = 3
*.server.app[0..2].typename = "UdpBasicApp"
*.server.app[0..2].packetName = "UdpBasicApp" + string(index)
*.server.app[0..2].destAddresses = "host[" + string(index) + "]"
*.server.app[0..2].messageLength = 1000B
*.server.app[0..2].sendInterval = 1ms
*.server.app[0..2].startTime = 0.2s
*.server.app[0..2].stopTime = 1.9s
*.server.app[0].destPort = 5000
*.server.app[1].destPort = 5001
*.server.app[2].destPort = 5002

*.host[*].numApps = 1
*.host[*].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000
*.host[1].app[0].localPort = 5001
*.host[2].app[0].localPort = 5002


[Config FixedVhtMcs]
description = "VHT 802.11ac fixed MCS 9 without dynamic rate adaptation"
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].radio.transmitter.mcs = 9

[Config VhtMinstrelAdaptation]
description = "VHT 802.11ac dynamic Minstrel rate adaptation algorithm"
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].mac.hcf.rateControl.typename = "Ieee80211VhtMinstrel"
