[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

# BSS setup in 5 GHz 80 MHz channel
**.opMode = "ac"
**.bandName = "5 GHz (80 MHz)"
**.numHosts = 2

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[0].mobility.initialY = 200m
**.host[1].mobility.initialX = 270m
**.host[1].mobility.initialY = 200m

# UDP traffic setup from server to host[0]
*.server.numApps = 1
*.server.app[0].typename = "UdpBasicApp"
*.server.app[0].destAddresses = "host[0]"
*.server.app[0].destPort = 5000
*.server.app[0].messageLength = 1400B
*.server.app[0].sendInterval = 0.1ms
*.server.app[0].startTime = 0.2s
*.server.app[0].stopTime = 0.9s

*.host[0].numApps = 1
*.host[0].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000


[Config Base]
abstract = true
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].mac.hcf.rateControl.typename = ""

[Config BaselineHtMcs7]
description = "HT MCS 7 baseline (64-QAM 5/6 coding rate, 65 Mbps)"
extends = Base
**.opMode = "n(mixed-2.4Ghz)"
**.bandName = "2.4 GHz (20 MHz)"
**.wlan[*].radio.transmitter.mcs = 7

[Config VhtMcs7]
description = "VHT MCS 7 rate in 80 MHz channel (64-QAM 5/6, 325 Mbps)"
extends = Base
**.wlan[*].radio.transmitter.mcs = 7

[Config VhtMcs8_256QAM]
description = "VHT MCS 8 rate 256-QAM in 80 MHz channel (256-QAM 3/4, 390 Mbps)"
extends = Base
**.wlan[*].mac.hcf.rateControl.typename = "Ieee80211VhtMinstrel"

[Config VhtMcs9_256QAM]
description = "VHT MCS 9 rate 256-QAM in 80 MHz channel (256-QAM 5/6, 433.3 Mbps)"
extends = Base
**.wlan[*].radio.transmitter.mcs = 9
