[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

**.wlan[*].classifier.typename = "ExampleQosClassifier"
**.wlan[*].mac.qosStation = true

# BSS setup in 5 GHz 80 MHz channel
**.opMode = "ac"
**.bandName = "5 GHz (80 MHz)"
**.numHosts = 3

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.arp.typename = "GlobalArp"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[*].mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[1].mobility.initialX = 270m
**.host[2].mobility.initialX = 280m

# Identical UDP traffic setup from server to all hosts
*.server.numApps = 3
*.server.app[0..2].typename = "UdpBasicApp"
*.server.app[0..2].packetName = "UdpBasicApp" + string(index)
*.server.app[0..2].destAddresses = "host[" + string(index) + "]"
*.server.app[0..2].messageLength = 1400B
*.server.app[0..2].sendInterval = 0.1ms
*.server.app[0..2].startTime = 0.2s
*.server.app[0..2].stopTime = 0.9s
*.server.app[0].destPort = 5000
*.server.app[1].destPort = 5001
*.server.app[2].destPort = 5002

*.host[*].numApps = 1
*.host[*].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000
*.host[1].app[0].localPort = 5001
*.host[2].app[0].localPort = 5002


[Config Base]
abstract = true
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].mac.hcf.rateSelection.mgmtFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.controlFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseAckFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseBlockAckFrameBitrate = 6Mbps

[Config BaselineHtMcs7]
description = "HT MCS 7 baseline (64-QAM 5/6 coding rate, 65 Mbps)"
extends = Base
**.opMode = "n(mixed-2.4Ghz)"
**.bandName = "2.4 GHz (20 MHz)"
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 65Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 20MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1

[Config VhtMcs7]
description = "VHT MCS 7 rate in 80 MHz channel (64-QAM 5/6, 325 Mbps)"
extends = Base
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 292.5Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1

[Config VhtMcs8_256QAM]
description = "VHT MCS 8 rate in 80 MHz channel (256-QAM 3/4, 351 Mbps)"
extends = Base
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 351Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1

[Config VhtMcs9_256QAM]
description = "VHT MCS 9 rate 256-QAM in 80 MHz channel (256-QAM 5/6, 433.3 Mbps)"
extends = Base
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 390Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1
