[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

# BSS setup in 5 GHz
**.opMode = "ac"
**.numHosts = 2

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[0].mobility.initialY = 200m
**.host[1].mobility.initialX = 270m
**.host[1].mobility.initialY = 200m

# UDP traffic setup from server to host[0]
*.server.numApps = 1
*.server.app[0].typename = "UdpBasicApp"
*.server.app[0].destAddresses = "host[0]"
*.server.app[0].destPort = 5000
*.server.app[0].messageLength = 1400B
*.server.app[0].sendInterval = 0.1ms
*.server.app[0].startTime = 0.2s
*.server.app[0].stopTime = 0.9s

[Config Base]
abstract = true
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].bitrate = 65Mbps

[Config Vht20MHz]
description = "VHT 802.11ac 20 MHz channel operation in 5 GHz"
extends = Base
**.bandName = "5 GHz (20 MHz)"

[Config Vht40MHz]
description = "VHT 802.11ac 40 MHz channel operation in 5 GHz"
extends = Base
**.bandName = "5 GHz (40 MHz)"

[Config Vht80MHz]
description = "VHT 802.11ac 80 MHz wide channel operation in 5 GHz"
extends = Base
**.bandName = "5 GHz (80 MHz)"

[Config Vht160MHz]
description = "VHT 802.11ac 160 MHz wide channel operation in 5 GHz"
extends = Base
**.bandName = "5 GHz (160 MHz)"
