[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

# BSS setup
**.opMode = "n(mixed-2.4Ghz)"
**.numHosts = 2

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[0].mobility.initialY = 200m
**.host[1].mobility.initialX = 270m
**.host[1].mobility.initialY = 200m

# UDP traffic setup
*.server.numApps = 1
*.server.app[0].typename = "UdpBasicApp"
*.server.app[0].destAddresses = "host[0]"
*.server.app[0].destPort = 5000
*.server.app[0].messageLength = 1000B
*.server.app[0].sendInterval = 0.2ms
*.server.app[0].startTime = 0.2s
*.server.app[0].stopTime = 0.9s

*.host[0].numApps = 1
*.host[0].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000


[Config LongGI800ns]
description = "HT 802.11n Standard Long Guard Interval (800 ns)"
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].bitrate = 65Mbps
**.wlan[*].radio.transmitter.guardInterval = 800ns

[Config ShortGI400ns]
description = "HT 802.11n Short Guard Interval (400 ns)"
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].bitrate = 65Mbps
**.wlan[*].radio.transmitter.guardInterval = 400ns
