[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

**.wlan[*].classifier.typename = "ExampleQosClassifier"
**.wlan[*].mac.qosStation = true
**.wlan[*].mac.hcf.rateSelection.mgmtFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.controlFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseAckFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseBlockAckFrameBitrate = 6Mbps

# BSS setup in 5 GHz
**.opMode = "ac"
**.numHosts = 3

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.arp.typename = "GlobalArp"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[*].mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[1].mobility.initialX = 270m
**.host[2].mobility.initialX = 280m

# High-throughput UDP traffic setup
*.server.numApps = 3
*.server.app[0..2].typename = "UdpBasicApp"
*.server.app[0..2].packetName = "UdpBasicApp" + string(index)
*.server.app[0..2].destAddresses = "host[" + string(index) + "]"
*.server.app[0..2].messageLength = 1000B
*.server.app[0..2].sendInterval = 0.1ms
*.server.app[0..2].startTime = 0.2s
*.server.app[0..2].stopTime = 0.5s
*.server.app[0].destPort = 5000
*.server.app[1].destPort = 5001
*.server.app[2].destPort = 5002

*.host[*].numApps = 1
*.host[*].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000
*.host[1].app[0].localPort = 5001
*.host[2].app[0].localPort = 5002


[Config Base]
abstract = true
**.wlan[*].bitrate = 65Mbps
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.bandName = "5 GHz (80 MHz)"

[Config VhtLongGI]
description = "VHT 802.11ac Long Guard Interval (800 ns) in 80 MHz channel"
extends = Base
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 351Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1

[Config VhtShortGI]
description = "VHT 802.11ac Short Guard Interval (400 ns) in 80 MHz channel"
extends = Base
**.wlan[*].mib.vhtShortGi80 = true
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 433.3Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 80MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1
