[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

# BSS setup
**.opMode = "n(mixed-2.4Ghz)"
**.numHosts = 2

# Position nodes
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[0].mobility.initialY = 200m
**.host[1].mobility.initialX = 270m
**.host[1].mobility.initialY = 200m

# UDP traffic setup from server to host[0]
*.server.numApps = 1
*.server.app[0].typename = "UdpBasicApp"
*.server.app[0].destAddresses = "host[0]"
*.server.app[0].destPort = 5000
*.server.app[0].messageLength = 1000B
*.server.app[0].sendInterval = 0.2ms
*.server.app[0].startTime = 0.2s
*.server.app[0].stopTime = 0.9s

*.host[0].numApps = 1
*.host[0].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000


[Config Base]
description = "Base HT configuration with Block Ack enabled"
abstract = true
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].bitrate = 65Mbps

[Config NoAggregation]
description = "HT 802.11n without MSDU or MPDU frame aggregation"
extends = Base
**.wlan[*].mac.hcf.originatorMacDataService.msduAggregationPolicy.typename = ""
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = ""

[Config AMsduOnly]
description = "HT 802.11n with A-MSDU frame aggregation only"
extends = Base
**.wlan[*].mac.hcf.originatorMacDataService.msduAggregationPolicy.typename = "Ieee80211MsduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = ""
**.wlan[*].mac.hcf.originatorMacDataService.msduAggregationPolicy.maxAMsduSize = 3839B

[Config AMpduOnly]
description = "HT 802.11n with A-MPDU frame aggregation only"
extends = Base
**.wlan[*].mac.hcf.originatorMacDataService.msduAggregationPolicy.typename = ""
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = "Ieee80211MpduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.maxAMpduSize = 65535B

[Config TwoLevelAggregation]
description = "HT 802.11n two-level aggregation (A-MSDU inside A-MPDU)"
extends = Base
**.wlan[*].mac.hcf.originatorMacDataService.msduAggregationPolicy.typename = "Ieee80211MsduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.typename = "Ieee80211MpduAggregationPolicy"
**.wlan[*].mac.hcf.originatorMacDataService.msduAggregationPolicy.maxAMsduSize = 3839B
**.wlan[*].mac.hcf.originatorMacDataService.mpduAggregationPolicy.maxAMpduSize = 65535B
