[General]
network = inet.examples.ieee80211.common.SingleBssNetwork
sim-time-limit = 1s

# BSS setup
**.opMode = "n(mixed-2.4Ghz)"
**.numHosts = 3

# AP Address & Position
**.ap.wlan[*].address = "10:00:00:00:00:00"
**.host[*].**.mgmt.accessPointAddress = "10:00:00:00:00:00"
**.arp.typename = "GlobalArp"
**.ap.mobility.initialX = 250m
**.ap.mobility.initialY = 200m
**.host[*].mobility.initialY = 200m
**.host[0].mobility.initialX = 260m
**.host[1].mobility.initialX = 270m
**.host[2].mobility.initialX = 280m

# UDP traffic setup
*.server.numApps = 3
*.server.app[0..2].typename = "UdpBasicApp"
*.server.app[0..2].packetName = "UdpBasicApp" + string(index)
*.server.app[0..2].destAddresses = "host[" + string(index) + "]"
*.server.app[0..2].messageLength = 1200B
*.server.app[0..2].sendInterval = 0.1ms
*.server.app[0..2].startTime = 0.2s
*.server.app[0..2].stopTime = 0.9s
*.server.app[0].destPort = 5000
*.server.app[1].destPort = 5001
*.server.app[2].destPort = 5002

*.host[*].numApps = 1
*.host[*].app[0].typename = "UdpSink"
*.host[0].app[0].localPort = 5000
*.host[1].app[0].localPort = 5001
*.host[2].app[0].localPort = 5002


[Config Base]
abstract = true
**.wlan[*].bitrate = 13Mbps
**.wlan[*].mac.hcf.isBlockAckSupported = true
**.wlan[*].classifier.typename = "ExampleQosClassifier"
**.wlan[*].mac.qosStation = true
**.wlan[*].mac.hcf.rateSelection.mgmtFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.controlFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseAckFrameBitrate = 6Mbps
**.wlan[*].mac.hcf.rateSelection.responseBlockAckFrameBitrate = 6Mbps

[Config SingleStreamMcs1]
description = "HT 1x1 Single Spatial Stream"
extends = Base
**.wlan[*].radio.antenna.numAntennas = 1
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].radio.transmitter.mcs = 1
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 13Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 20MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 1

[Config DualStreamMcs9]
description = "HT 2x2 Dual Spatial Stream"
extends = Base
**.wlan[*].radio.antenna.numAntennas = 2
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].radio.transmitter.mcs = 9
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 26Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 20MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 2

[Config QuadStreamMcs25]
description = "HT 4x4 Quad Spatial Stream"
extends = Base
**.wlan[*].radio.antenna.numAntennas = 4
**.wlan[*].mac.hcf.rateControl.typename = ""
**.wlan[*].radio.transmitter.mcs = 25
**.wlan[*].mac.hcf.rateSelection.dataFrameBitrate = 52Mbps
**.wlan[*].mac.hcf.rateSelection.dataFrameBandwidth = 20MHz
**.wlan[*].mac.hcf.rateSelection.dataFrameNumSpatialStreams = 4
