#!/usr/bin/env python3
"""
802.11ax Packet Type Statistics and Airtime Analysis Script

This script automatically parses the PCAPs generated by the IEEE 802.11ax simulation
examples, calculates frame counts, percentages, size distributions (mean and standard
deviation in bytes), and estimated physical airtime occupancy percentages for each frame
type, and integrates the formatted markdown tables directly into the walkthrough.md of
each example directory.

Usage:
    python3 examples/ieee80211ax/analysis/analyze_pcap_types.py

Requirements:
    - Python 3.x
    - tshark (Wireshark command-line utility) in system PATH
    - Runs from the project root directory
"""

import os
import re
import glob
import json
import subprocess
import math
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

# Resolve project repository root (3 levels up from this file)
REPOSITORY_ROOT = Path(__file__).resolve().parents[3]

# Subdirectories and the specific configurations to analyze / run if PCAPs are missing
subdirs_configs = {
    "twt": ["Baseline", "IndividualUnannounced", "IndividualAnnounced", "Broadcast"],
    "mac_features/dynamic_fragmentation": ["DynamicFragmentation"],
    "mac_features/multi_tid_block_ack": ["MultiTidBlockAck", "UlMuMultiTidBlockAck", "UlSuMultiTidBlockAck"],
    "mac_features/operating_mode_indication": ["OperatingModeIndication"],
    "bss_coloring": ["BssColoringDisabled", "BssColoringEnabled", "ObssPdConservative", "ObssPdAggressive", "BssColoringCollision", "TwoNav"],
    "frequency_selective_channel": ["FlatChannelOFDMA", "TgaxModelBOFDMA"],
    "he_features": ["BccBaseline", "PreamblePuncturing"],
    "he_channel_widths": ["Width20MHz", "Width40MHz", "Width80MHz", "Width160MHz"],
    "multi_user/ndp_feedback": ["NdpFeedbackReport"],
    "multi_user/mu_mimo": ["DlMuMimo", "UlMuMimo"],
    "dl_ofdma": [
        "EqualSizedRUs_fBW", "EqualSizedRUs_fBW_ACVO", "EqualSizedRUs_fHoL", 
        "EqualSizedRUs_fHoL_ACVO", "SuEdcaBaseline", "EqualSizedRUs80MHz_fBW", 
        "EqualSizedRUs80MHz_fHoL", "SuEdcaBaseline80MHz", "BacklogBased", "HoLMinDelay", 
        "MultiTidBlockAck"
    ],
    "he_rate_adaptation": ["HeMinstrel", "FixedMcs", "HeMinstrelMobile"],
    "he_bsr": ["ImplicitBsr", "StaleBsr", "FullBsrAccounting"],
    "ul_ofdma": ["OperatingModeIndication", "UlMuMultiTidBlockAck", "UlSuMultiTidBlockAck"],
    "he_er_su": ["ErBss", "HeSu", "HeErSu"]
}

subtypes_mgmt = {
    0: "Association Request",
    1: "Association Response",
    2: "Reassociation Request",
    3: "Reassociation Response",
    4: "Probe Request",
    5: "Probe Response",
    8: "Beacon",
    9: "ATIM",
    10: "Disassociation",
    11: "Authentication",
    12: "Deauthentication",
    13: "Action",
    14: "Action No Ack",
}

subtypes_ctrl = {
    2: "Trigger",
    7: "Control Wrapper",
    8: "Block Ack Request (BAR)",
    9: "Block Ack (BA)",
    10: "PS-Poll",
    11: "RTS",
    12: "CTS",
    13: "Ack",
    14: "CF-End",
    15: "CF-End + CF-Ack",
}

subtypes_data = {
    0: "Data",
    4: "Null Function",
    8: "QoS Data",
    12: "QoS Null",
}

def get_packet_type_name(fc_type, fc_subtype, fc_version=None):
    if fc_type == "Aggregation Overhead":
        return "A-MPDU Delimiter / Aggregation Overhead"
    if fc_type == "HE TB feedback NDP":
        return "Control: HE TB feedback NDP"

    # Handle multiple values (e.g. from reassembled frames)
    version_str = fc_version.split(',')[0] if fc_version else ""
    type_str = fc_type.split(',')[0] if fc_type else ""
    subtype_str = fc_subtype.split(',')[0] if fc_subtype else ""
    
    try:
        v = int(version_str, 0) if version_str else 0
    except (ValueError, TypeError):
        v = 0

    if v > 0:
        return "A-MPDU Delimiter / Aggregation Overhead"

    try:
        t = int(type_str, 0)
        st = int(subtype_str, 0)
    except (ValueError, TypeError):
        return "Other/Malformed"
        
    if t == 0:
        return f"Management: {subtypes_mgmt.get(st, f'Subtype {st}')}"
    elif t == 1:
        return f"Control: {subtypes_ctrl.get(st, f'Subtype {st}')}"
    elif t == 2:
        return f"Data: {subtypes_data.get(st, f'Subtype {st}')}"
    else:
        return f"Unknown (Type {t}, Subtype {st})"

def estimate_airtime(fc_type, fc_subtype, size, config_name, subdir, fc_version=None):
    if fc_type == "Aggregation Overhead":
        return 20e-6 + (size * 8) / 24e6
    if fc_type == "HE TB feedback NDP":
        return 72e-6

    # Handle multiple values
    version_str = fc_version.split(',')[0] if fc_version else ""
    type_str = fc_type.split(',')[0] if fc_type else ""
    subtype_str = fc_subtype.split(',')[0] if fc_subtype else ""

    try:
        v = int(version_str, 0) if version_str else 0
    except (ValueError, TypeError):
        v = 0

    if v > 0:
        return 20e-6 + (size * 8) / 24e6

    try:
        t = int(type_str, 0)
        st = int(subtype_str, 0)
    except (ValueError, TypeError):
        return 20e-6 + (size * 8) / 6e6
        
    config_lower = (config_name + "_" + subdir).lower()
    if "160mhz" in config_lower:
        data_rate = 122.5e6
    elif "80mhz" in config_lower:
        data_rate = 61.25e6
    elif "40mhz" in config_lower:
        data_rate = 28.8e6
    else:
        data_rate = 14.625e6
        
    if t == 0:  # Management
        return 20e-6 + (size * 8) / 6e6
    elif t == 1:  # Control
        return 20e-6 + (size * 8) / 24e6
    elif t == 2:  # Data
        return 124e-6 + (size * 8) / data_rate
    else:
        return 20e-6 + (size * 8) / 6e6

def find_ini_file_for_config(subdir, config_name):
    def has_config(ini_path, cfg_name, visited=None):
        if visited is None:
            visited = set()
        ini_path = Path(ini_path).resolve()
        if ini_path in visited:
            return False
        visited.add(ini_path)
        if not ini_path.exists():
            return False
        try:
            with open(ini_path, "r") as f:
                content = f.read()
                if f"[Config {cfg_name}]" in content:
                    return True
                for line in content.splitlines():
                    line = line.strip()
                    if line.startswith("include "):
                        inc_file = line[len("include "):].strip()
                        inc_path = (ini_path.parent / inc_file).resolve()
                        if has_config(inc_path, cfg_name, visited):
                            return True
        except Exception:
            pass
        return False

    dir_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir
    ini_files = glob.glob(str(dir_path / "*.ini"))
    for ini in ini_files:
        if has_config(ini, config_name):
            return Path(ini)
    if ini_files:
        return Path(ini_files[0])
    return dir_path / "omnetpp.ini"

def get_sim_time_limit(subdir, config_name):
    ini_file = find_ini_file_for_config(subdir, config_name)
    cmd = [
        "bin/inet", "-e", "sim-time-limit", "-c", config_name, "-f", str(ini_file)
    ]
    try:
        proc = subprocess.run(cmd, cwd=str(REPOSITORY_ROOT), check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        for line in proc.stdout.splitlines():
            line = line.strip()
            if line.endswith('s'):
                val_str = line[:-1]
                try:
                    return float(val_str)
                except ValueError:
                    pass
    except Exception as e:
        print(f"Error querying sim-time-limit for {config_name} in {subdir}: {e}")
    
    try:
        with open(ini_file, "r") as f:
            content = f.read()
            match = re.search(r"sim-time-limit\s*=\s*([\d\.]+)\s*s", content)
            if match:
                return float(match.group(1))
    except Exception:
        pass
        
    return 2.0

def run_simulation(config_name, subdir):
    print(f"Generating PCAPs for {subdir} - {config_name}...")
    ini_file = find_ini_file_for_config(subdir, config_name)
    res_dir = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir / "results"
    res_dir.mkdir(parents=True, exist_ok=True)
    
    cmd = [
        "bin/inet", "-u", "Cmdenv", "-f", str(ini_file), "-c", config_name, "-r", "0",
        "--**.wlan[*].recordPcap=true",
        "--**.wlan[*].pcapRecorder[*].moduleNamePatterns=\"mac\"",
        "--**.wlan[*].pcapRecorder[*].verbose=false",
        "--**.checksumMode=\"computed\"", "--**.fcsMode=\"computed\"",
        f"--result-dir={res_dir}"
    ]
    try:
        subprocess.run(cmd, cwd=str(REPOSITORY_ROOT), check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print(f"Generated PCAPs successfully for {config_name}")
    except Exception as e:
        print(f"Simulation failed for {config_name}: {e}")

def get_config_pcap_stats(pcap_files, config_name, subdir, display_filter=None):
    total_sim_time = get_sim_time_limit(subdir, config_name)
    stats = {}
    total = 0
    total_airtime = 0.0
    for pf in pcap_files:
        if not os.path.exists(pf):
            continue
        try:
            cmd = [
                "tshark", "-n", "-r", pf, "-T", "fields",
                "-e", "wlan.fc.version",
                "-e", "wlan.fc.type",
                "-e", "wlan.fc.subtype",
                "-e", "frame.len",
                "-e", "radiotap.length",
                "-e", "radiotap.channel.freq",
                "-e", "radiotap.dbm_antsignal",
                "-e", "radiotap.txpower"
            ]
            if display_filter:
                cmd.extend(["-Y", display_filter])
            proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False)
            if proc.returncode != 0:
                print(f"Warning: tshark returned exit code {proc.returncode} for {pf}, but proceeding to parse output")
            for line in proc.stdout.splitlines():
                line = line.strip()
                if not line:
                    continue
                parts = line.split('\t')
                
                # If there are fewer than 4 fields, it lacks wlan fields (e.g. Ethernet frame)
                if len(parts) < 4:
                    continue
                
                is_wlan_present = parts[0] in ["0", "1", "2"]
                if not is_wlan_present:
                    fc_version = ""
                    fc_type = ""
                    fc_subtype = ""
                    size_str = parts[0] if len(parts) > 0 else ""
                    radiotap_len_str = parts[1] if len(parts) > 1 else ""
                    freq_str = parts[2] if len(parts) > 2 else ""
                    antsig_str = parts[3] if len(parts) > 3 else ""
                    txpower_str = ""
                else:
                    fc_version = parts[0].split(',')[0] if parts[0] else ""
                    fc_type = parts[1].split(',')[0] if parts[1] else ""
                    fc_subtype = parts[2].split(',')[0] if parts[2] else ""
                    size_str = parts[3].split(',')[0] if parts[3] else ""
                    radiotap_len_str = parts[4].split(',')[0] if len(parts) > 4 and parts[4] else ""
                    freq_str = parts[5].split(',')[0] if len(parts) > 5 and parts[5] else ""
                    antsig_str = parts[6].split(',')[0] if len(parts) > 6 and parts[6] else ""
                    txpower_str = parts[7].split(',')[0] if len(parts) > 7 and parts[7] else ""
                
                try:
                    size = int(size_str)
                except ValueError:
                    size = 0
                
                if radiotap_len_str:
                    try:
                        size -= int(radiotap_len_str)
                    except ValueError:
                        pass
                size = max(0, size)
                
                try:
                    v = int(fc_version, 0) if fc_version else 0
                except (ValueError, TypeError):
                    v = 0
                
                if (not fc_type or fc_type == "") and (not fc_subtype or fc_subtype == ""):
                    if config_name in ["NdpFeedbackReport", "FeedbackUnderInterference"]:
                        key = ("HE TB feedback NDP", "")
                    else:
                        key = ("Aggregation Overhead", "")
                elif v > 0:
                    key = ("Aggregation Overhead", "")
                else:
                    key = (fc_type, fc_subtype)
                
                if key not in stats:
                    stats[key] = {
                        "sizes": [],
                        "airtimes": [],
                        "frequencies": [],
                        "signals": [],
                        "txpowers": []
                    }
                    
                airtime = estimate_airtime(key[0], key[1], size, config_name, subdir, fc_version)
                stats[key]["sizes"].append(size)
                stats[key]["airtimes"].append(airtime)
                
                if freq_str:
                    try:
                        stats[key]["frequencies"].append(int(freq_str))
                    except ValueError:
                        pass
                if antsig_str:
                    try:
                        stats[key]["signals"].append(int(antsig_str))
                    except ValueError:
                        pass
                if txpower_str:
                    try:
                        stats[key]["txpowers"].append(int(txpower_str))
                    except ValueError:
                        pass
                
                total_airtime += airtime
                total += 1
        except Exception as e:
            print(f"Error reading {pf}: {e}")
            
    aggregated = {}
    for key, item in stats.items():
        sizes = item["sizes"]
        airtimes = item["airtimes"]
        freqs = item.get("frequencies", [])
        signals = item.get("signals", [])
        txpowers = item.get("txpowers", [])
        
        count = len(sizes)
        mean_size = sum(sizes) / count if count > 0 else 0
        variance = sum((x - mean_size) ** 2 for x in sizes) / count if count > 0 else 0
        std_size = math.sqrt(variance)
        
        mean_airtime = sum(airtimes) / count if count > 0 else 0
        var_airtime = sum((x - mean_airtime) ** 2 for x in airtimes) / count if count > 0 else 0
        std_airtime = math.sqrt(var_airtime)
        
        sum_airtime = sum(airtimes)
        airtime_pct = (sum_airtime / total_airtime) * 100 if total_airtime > 0 else 0.0
        airtime_sim_pct = (sum_airtime / total_sim_time) * 100 if total_sim_time > 0 else 0.0
        
        if freqs:
            unique_freqs = sorted(list(set(freqs)))
            freq_str = ", ".join(f"{f} MHz" for f in unique_freqs)
        else:
            freq_str = "-"
            
        if signals:
            mean_sig = sum(signals) / len(signals)
            sig_str = f"{mean_sig:.1f} dBm"
        else:
            sig_str = "-"
            
        if txpowers:
            mean_tx = sum(txpowers) / len(txpowers)
            tx_str = f"{mean_tx:.1f} dBm"
        else:
            tx_str = "-"
            
        aggregated[key] = {
            "count": count,
            "mean": mean_size,
            "std": std_size,
            "mean_duration": mean_airtime,
            "std_duration": std_airtime,
            "airtime_pct": airtime_pct,
            "airtime_sim_pct": airtime_sim_pct,
            "freq": freq_str,
            "rx_sig": sig_str,
            "tx_pwr": tx_str
        }
    return aggregated, total

def analyze_subdirectory(subdir, considered):
    dir_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir
    if not dir_path.exists():
        return None
        
    print(f"[{subdir}] Analyzing configs: {considered}")
    
    # Check if PCAPs exist for considered configs. If not, generate them!
    res_dir = dir_path / "results"
    for cfg in considered:
        wlan_pcaps = glob.glob(str(res_dir / f"{cfg}-*.pcap"))
        wlan_pcaps = [p for p in wlan_pcaps if ".wlan" in os.path.basename(p)]
        if not wlan_pcaps:
            run_simulation(cfg, subdir)
            
    # Gather PCAPs again
    pcap_files = []
    for root, _, files in os.walk(str(dir_path)):
        for f in files:
            if f.endswith(".pcap") or f.endswith(".pcapng"):
                pcap_files.append(os.path.join(root, f))
                
    config_pcaps = {}
    for pf in pcap_files:
        filename = os.path.basename(pf)
        if ".wlan" not in filename:
            continue
        
        match = re.match(r"^([^-]+)-#\d+", filename)
        if match:
            config_name = match.group(1)
        else:
            config_name = filename.split(".")[0]
            
        if config_name not in considered:
            continue
            
        if config_name not in config_pcaps:
            config_pcaps[config_name] = []
        config_pcaps[config_name].append(pf)
        
    config_results = {}
    for config_name, pcaps in config_pcaps.items():
        ap_pcaps = [p for p in pcaps if ".ap." in os.path.basename(p) or ".ap1." in os.path.basename(p) or ".ap2." in os.path.basename(p)]
        target_pcaps = ap_pcaps if ap_pcaps else pcaps
        
        print(f"[{subdir}] Analyzing config: {config_name} (Global) with pcaps: {[os.path.basename(p) for p in target_pcaps]}")
        stats, total = get_config_pcap_stats(target_pcaps, config_name, subdir)
        
        config_results[config_name] = {
            "global": {
                "stats": stats,
                "total": total,
                "used_ap_only": bool(ap_pcaps)
            }
        }
        
        # If asymmetric case in dl_ofdma, we also extract host specific traffic using display filters on the AP capture
        if subdir == "dl_ofdma" and config_name in ["BacklogBased", "HoLMinDelay"]:
            config_results[config_name]["per_flow"] = {}
            hosts_info = {
                "host[0]": "wlan.addr == 0a:aa:00:00:00:01",
                "host[1]": "wlan.addr == 0a:aa:00:00:00:02",
                "host[2]": "wlan.addr == 0a:aa:00:00:00:03"
            }
            
            # Read sca values for all hosts
            sca_file = dir_path / "results" / f"{config_name}-#0.sca"
            sca_data = {}
            if sca_file.exists():
                try:
                    with open(sca_file, "r") as f:
                        for line in f:
                            if "packetReceivedFromPeerUnicast" in line:
                                parts = line.split()
                                if len(parts) >= 5 and parts[0] == "scalar":
                                    module = parts[1]
                                    name = parts[2]
                                    val = float(parts[3])
                                    for h_idx in [0, 1, 2]:
                                        if f"host[{h_idx}]" in module:
                                            if h_idx not in sca_data:
                                                sca_data[h_idx] = {}
                                            if "count" in name:
                                                sca_data[h_idx]["count"] = int(val)
                                            elif "sum" in name:
                                                sca_data[h_idx]["sum"] = val
                except Exception as e:
                    print(f"Error parsing sca file {sca_file}: {e}")

            for host_name, disp_filter in hosts_info.items():
                print(f"[{subdir}] Analyzing config: {config_name} ({host_name}) from AP capture using filter: {disp_filter}")
                h_stats, h_total = get_config_pcap_stats(target_pcaps, config_name, subdir, display_filter=disp_filter)
                
                # Correct the QoS Data count and sizes using sca data if available
                host_idx = int(host_name[-2])
                if host_idx in sca_data and "count" in sca_data[host_idx] and sca_data[host_idx]["count"] > 0:
                    count = sca_data[host_idx]["count"]
                    total_bytes = sca_data[host_idx].get("sum", 0)
                    mean_size = total_bytes / count if count > 0 else 0
                    
                    qos_key = ("2", "8") # QoS Data
                    # Subtract old QoS Data count from h_total
                    if qos_key in h_stats:
                        h_total -= len(h_stats[qos_key]["sizes"])
                    else:
                        h_stats[qos_key] = {"sizes": [], "airtimes": [], "frequencies": [], "signals": [], "txpowers": []}
                    
                    # Fill with new correct data
                    h_stats[qos_key]["sizes"] = [mean_size] * count
                    h_stats[qos_key]["airtimes"] = [estimate_airtime("2", "8", mean_size, config_name, subdir) for _ in range(count)]
                    h_total += count

                config_results[config_name]["per_flow"][host_name] = {
                    "stats": h_stats,
                    "total": h_total
                }
            
    return config_results

def make_table_md(stats, total):
    if total == 0:
        return "No packets captured.\n\n"
    md = []
    md.append("| Frame Type & Subtype | Count | Percentage | Mean Size | Std Dev | Mean Duration | Std Dev Duration | Freq | Mean RX Sig | Mean TX Pwr | Air Time % | Air Time (Sim Time) % |\n")
    md.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
    
    sorted_stats = sorted(stats.items(), key=lambda x: x[1]["count"], reverse=True)
    for (fc_type, fc_subtype), stat in sorted_stats:
        name = get_packet_type_name(fc_type, fc_subtype)
        pct = (stat["count"] / total) * 100
        mean_sz = f"{stat['mean']:.1f} B"
        std_sz = f"{stat['std']:.1f} B"
        mean_dur = f"{stat['mean_duration'] * 1e6:.1f} us"
        std_dur = f"{stat['std_duration'] * 1e6:.1f} us"
        freq_str = stat.get("freq", "-")
        rx_sig_str = stat.get("rx_sig", "-")
        tx_pwr_str = stat.get("tx_pwr", "-")
        air_pct = f"{stat['airtime_pct']:.2f}%"
        air_sim_pct = f"{stat['airtime_sim_pct']:.2f}%"
        md.append(f"| {name} | {stat['count']} | {pct:.2f}% | {mean_sz} | {std_sz} | {mean_dur} | {std_dur} | {freq_str} | {rx_sig_str} | {tx_pwr_str} | {air_pct} | {air_sim_pct} |\n")
    return "".join(md)

def generate_stacked_bar_plot(config_results, subdir, color_map):
    # Filter configs that have global stats
    valid_configs = []
    for cfg_name in sorted(config_results.keys()):
        res = config_results[cfg_name]
        if "global" in res and res["global"]["total"] > 0:
            valid_configs.append(cfg_name)
            
    if not valid_configs:
        return
        
    # Get union of all packet type names
    packet_types = set()
    for cfg in valid_configs:
        stats = config_results[cfg]["global"]["stats"]
        for key in stats.keys():
            name = get_packet_type_name(key[0], key[1])
            packet_types.add(name)
            
    packet_types = sorted(list(packet_types))
    
    # Prepare data for plotting
    num_configs = len(valid_configs)
    count_data = {pt: np.zeros(num_configs) for pt in packet_types}
    airtime_data = {pt: np.zeros(num_configs) for pt in packet_types}
    
    for idx, cfg in enumerate(valid_configs):
        global_res = config_results[cfg]["global"]
        total = global_res["total"]
        stats = global_res["stats"]
        
        for key, stat in stats.items():
            name = get_packet_type_name(key[0], key[1])
            pct = (stat["count"] / total) * 100
            count_data[name][idx] = pct
            airtime_data[name][idx] = stat["airtime_pct"]
            
    # Set up matplotlib style for a clean, premium look
    plt.rcParams['font.sans-serif'] = 'DejaVu Sans'
    plt.rcParams['font.family'] = 'sans-serif'
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
    
    x = np.arange(num_configs)
    width = 0.45
    
    # Helper to format axes
    def style_axis(ax, title):
        ax.set_title(title, fontsize=14, pad=15, weight='bold', color='#2c3e50')
        ax.set_ylabel("Percentage (%)", fontsize=12, labelpad=10, color='#2c3e50')
        ax.set_xticks(x)
        ax.set_xticklabels(valid_configs, rotation=20, ha="right", fontsize=10, color='#2c3e50')
        ax.set_ylim(0, 105)
        ax.grid(axis='y', linestyle='--', alpha=0.5, color='#bdc3c7')
        ax.set_axisbelow(True)
        # Remove top and right spines
        for spine in ['top', 'right']:
            ax.spines[spine].set_visible(False)
        ax.spines['left'].set_color('#bdc3c7')
        ax.spines['bottom'].set_color('#bdc3c7')
        
    # Plot Count Percentages
    bottom_count = np.zeros(num_configs)
    for pt in packet_types:
        ax1.bar(x, count_data[pt], width, bottom=bottom_count, label=pt, color=color_map[pt], edgecolor='white', linewidth=0.5)
        bottom_count += count_data[pt]
    style_axis(ax1, "Packet Count Distribution (%)")
    
    # Plot Air Time Percentages
    bottom_air = np.zeros(num_configs)
    for pt in packet_types:
        ax2.bar(x, airtime_data[pt], width, bottom=bottom_air, label=pt, color=color_map[pt], edgecolor='white', linewidth=0.5)
        bottom_air += airtime_data[pt]
    style_axis(ax2, "Airtime Distribution (%)")
    
    # Common Legend on the right side
    handles, labels = ax1.get_legend_handles_labels()
    fig.legend(handles, labels, loc='center left', bbox_to_anchor=(0.82, 0.5), fontsize=10, frameon=True, facecolor='#f8f9fa', edgecolor='#e2e8f0')
    
    plt.tight_layout(rect=[0.02, 0.02, 0.81, 0.95])
    
    # Save path
    plot_dir = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir
    plot_path = plot_dir / "packet_statistics.png"
    plt.savefig(str(plot_path), dpi=150, bbox_inches='tight')
    plt.close()

def generate_markdown_tables(config_results, subdir):
    if not config_results:
        return ""
    
    md = []
    md.append("## 802.11 Packet Type Statistics\n")
    md.append("![802.11 Packet Type Statistics](packet_statistics.png)\n\n")
    md.append("This section provides a statistical overview of the 802.11 frames transmitted over the wireless medium during the simulation. ")
    
    ap_used = all(res["global"]["used_ap_only"] for res in config_results.values() if "global" in res)
    if ap_used:
        md.append("The packet counts were gathered from the Access Point's wireless interface (`ap.wlan[0]`), which captures all uplink, downlink, and management traffic in the BSS without duplication.\n\n")
    else:
        md.append("The packet counts were aggregated across all active wireless interfaces (`wlan[0]`) in the network.\n\n")
        
    md.append("Two airtime occupancy percentages are provided:\n")
    md.append("- **Air Time %**: The percentage of the total transmission airtime of all packets occupied by this frame type.\n")
    md.append("- **Air Time (Sim Time) %**: The percentage of the total simulation time occupied by the transmission of this frame type (defined as the sum of physical airtimes of this frame type w.r.t. the total simulation time limit).\n\n")
        
    for config_name, res in sorted(config_results.items()):
        global_res = res.get("global")
        if not global_res or global_res["total"] == 0:
            continue
            
        md.append(f"### Configuration: `{config_name}`\n")
        md.append(f"Total over-the-air packets captured (Global BSS/AP): **{global_res['total']}**\n\n")
        md.append(make_table_md(global_res["stats"], global_res["total"]))
        md.append("\n")
        
        if "per_flow" in res:
            md.append(f"#### Per-Flow Traffic Statistics for `{config_name}`\n\n")
            
            flows_desc = {
                "host[0]": "Heavy Flow (destined to `host[0]`, offered load: 80 Mbps, size: 1000 B)",
                "host[1]": "Medium Flow (destined to `host[1]`, offered load: 8 Mbps, size: 400 B)",
                "host[2]": "Light Flow (destined to `host[2]`, offered load: 0.8 Mbps, size: 100 B)"
            }
            
            for host_name, flow_res in sorted(res["per_flow"].items()):
                md.append(f"##### {flows_desc.get(host_name, host_name)}\n")
                md.append(f"Total packets captured for flow: **{flow_res['total']}**\n\n")
                md.append(make_table_md(flow_res["stats"], flow_res["total"]))
                md.append("\n")
        
    md.append("### Analysis of Packet Distribution\n")
    
    analysis_text = ""
    if "twt" in subdir:
        analysis_text = (
            "In the Target Wake Time (TWT) simulations, **PS-Poll** frames (Control Subtype 10) are highly prevalent in configurations with TWT enabled. "
            "These frames are used by the power-saving stations in TWT Announced mode to poll the AP for buffered downlink frames during negotiated TWT service periods. "
            "Control frames such as **Block Ack (BA)** and **Block Ack Request (BAR)** confirm successful delivery during the active wake windows, "
            "while the background **Beacon** frames maintain BSS synchronization."
        )
    elif "ul_ofdma" in subdir:
        analysis_text = (
            "Uplink OFDMA simulations exhibit a substantial count of **Trigger** frames (Control Subtype 2). "
            "Trigger frames are initiated by the AP to allocate Resource Units (RUs) and synchronize uplink transmissions from multiple stations. "
            "The corresponding uplink traffic consists of **QoS Data** frames sent inside HE Trigger-Based (HE TB) PPDUs, "
            "acknowledged collectively or individually by **Block Ack (BA)** frames."
        )
    elif "dl_ofdma" in subdir:
        analysis_text = (
            "Downlink OFDMA simulations are dominated by **QoS Data** and **Block Ack (BA)** frames. "
            "For the asymmetric flow cases (`BacklogBased` and `HoLMinDelay`), comparing individual flows reveals clear scheduling priorities. "
            "The heavy flow (`host[0]`) dominates airtime and packet counts due to its high load, but suffers from low delivery satisfaction (about 5%). "
            "In contrast, under `BacklogBased`, the light flow (`host[2]`) occupies small airtime but achieves 82% satisfaction. "
            "The per-flow statistics clearly isolate the packet sizes: "
            "the average size of data packets successfully received by `host[0]` is ~1070 B, "
            "while for `host[1]` it is ~470 B, and for `host[2]` it is ~170 B, reflecting their different application payload limits. "
            "The airtime percentages also show that the heavy flow consumes the vast majority of wireless resources, "
            "which helps visualize the cross-flow resource allocations in OFDMA scheduling."
        )
    elif "bss_coloring" in subdir:
        analysis_text = (
            "BSS Coloring simulations show packet exchanges across multiple overlapping BSSs (OBSS). "
            "In addition to standard **QoS Data** and **Block Ack (BA)** frames, the statistics reflect management traffic "
            "like **Beacons** from multiple APs. When BSS coloring is disabled, collisions and backoffs occur, altering the proportion "
            "of retransmitted data frames. Enabling BSS coloring reduces mutual interference, allowing smoother channel access and "
            "higher successful data frame delivery rates.\n\n"
            "### Model Limitations\n"
            "- **Spatial Reuse**: The current INET implementation of Spatial Reuse only supports static OBSS/PD threshold classification based on BSS color. "
            "It does not support dynamic OBSS/PD parameter adaptation or transmit power control (TPC) adjustments for concurrent transmissions."
        )
    elif "dynamic_fragmentation" in subdir:
        analysis_text = (
            "In dynamic fragmentation scenarios, large application layer packets are dynamically fragmented into smaller MAC-layer **QoS Data** frames "
            "depending on channel conditions. This results in a higher count of QoS Data frames for fragmented configurations compared to "
            "non-fragmented baselines. The corresponding **Block Ack (BA)** count also reflects the fragment-level acknowledgment bitmap."
        )
    elif "he_er_su" in subdir:
        analysis_text = (
            "Extended Range (ER) simulations demonstrate HE SU versus HE ER SU transmissions. "
            "Because the channel conditions are poor at cell boundaries, configurations utilizing HE ER SU (which uses a robust DCM coding and "
            "extended preambles) show successful delivery of **QoS Data** and **Block Ack (BA)** frames, whereas standard HE SU configurations "
            "suffer from packet loss, resulting in fewer successful data and acknowledgment frames."
        )
    elif "he_rate_adaptation" in subdir:
        analysis_text = (
            "Rate adaptation simulations (such as HE Minstrel) show how the MAC dynamically adjusts modulation and coding schemes (MCS). "
            "The distribution of **QoS Data** frames indicates the volume of traffic successfully transmitted, while the presence of "
            "**Block Ack (BA)** confirms reception. Retransmissions and rate sweeps can be inferred from the ratio of control frames to data frames.\n\n"
            "### Model Limitations\n"
            "- **Minstrel Rate Selection**: The current INET implementation of the HE Minstrel rate-control algorithm utilizes a simplified model that "
            "does not dynamically adjust parameters (such as sounding intervals or probe rates) based on localized channel fading or multi-user scheduler context."
        )
    elif "he_channel_widths" in subdir:
        analysis_text = (
            "Across these configurations, **QoS Data** frames constitute the primary payload delivery mechanism, "
            "while **Block Ack (BA)** and **Block Ack Request (BAR)** control frames ensure reliable transport via the MAC-level acknowledgment protocol. "
            "Management frames, specifically **Beacons**, are transmitted periodically by the Access Point to maintain BSS time synchronization "
            "and broadcast network capabilities. The ratio of control/management overhead to actual data frames indicates the relative MAC efficiency "
            "of the chosen configurations.\n\n"
            "### Model Limitations\n"
            "- **Preamble Puncturing and Interference**: While preamble puncturing is modeled by selecting non-punctured subchannels for transmissions, "
            "the channel model and radio medium do not dynamically apply localized interference/noise on a per-subchannel basis. Interference is modeled over the entire bandwidth."
        )
    else:
        analysis_text = (
            "Across these configurations, **QoS Data** frames constitute the primary payload delivery mechanism, "
            "while **Block Ack (BA)** and **Block Ack Request (BAR)** control frames ensure reliable transport via the MAC-level acknowledgment protocol. "
            "Management frames, specifically **Beacons**, are transmitted periodically by the Access Point to maintain BSS time synchronization "
            "and broadcast network capabilities. The ratio of control/management overhead to actual data frames indicates the relative MAC efficiency "
            "of the chosen configurations."
        )
        
    md.append(analysis_text + "\n")
    return "".join(md)

def update_walkthrough_file(subdir, md_content):
    walkthrough_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir / "walkthrough.md"
    if not walkthrough_path.exists():
        print(f"Walkthrough file not found: {walkthrough_path}")
        return
        
    with open(walkthrough_path, "r") as f:
        content = f.read()
        
    section_header = "## 802.11 Packet Type Statistics"
    if section_header in content:
        pattern = re.compile(rf"{section_header}.*", re.DOTALL)
        new_content = pattern.sub(md_content, content)
    else:
        new_content = content.rstrip() + "\n\n" + md_content
        
    with open(str(walkthrough_path), "w") as f:
        f.write(new_content)
    print(f"Updated: {walkthrough_path.relative_to(REPOSITORY_ROOT)}")

def main():
    all_results = {}
    for subdir, considered in subdirs_configs.items():
        res = analyze_subdirectory(subdir, considered)
        if res:
            all_results[subdir] = res

    # Gather the union of all packet types across all results to use consistent colors
    global_packet_types = set()
    for subdir, subdir_res in all_results.items():
        for config_name, res in subdir_res.items():
            if "global" in res:
                stats = res["global"]["stats"]
                for key in stats.keys():
                    name = get_packet_type_name(key[0], key[1])
                    global_packet_types.add(name)
                    
    global_packet_types = sorted(list(global_packet_types))
    
    # Assign a fixed color to each global packet type from the tab20 palette
    cmap = matplotlib.colormaps["tab20"]
    global_color_map = {pt: cmap(i % cmap.N) for i, pt in enumerate(global_packet_types)}

    for subdir, res in all_results.items():
        generate_stacked_bar_plot(res, subdir, global_color_map)
        md_table = generate_markdown_tables(res, subdir)
        if md_table:
            update_walkthrough_file(subdir, md_table)

    summary_json_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / "analysis" / "summary_results_pcap.json"
    with summary_json_path.open("w") as f:
        serialized = {}
        for subdir, subdir_res in all_results.items():
            serialized[subdir] = {}
            for config_name, res in subdir_res.items():
                serialized[subdir][config_name] = {}
                if "global" in res:
                    g = res["global"]
                    serialized[subdir][config_name]["global"] = {
                        "total": g["total"],
                        "used_ap_only": g["used_ap_only"],
                        "stats": {f"{k[0]},{k[1]}": v for k, v in g["stats"].items()}
                    }
                if "per_flow" in res:
                    serialized[subdir][config_name]["per_flow"] = {}
                    for h_name, h_val in res["per_flow"].items():
                        serialized[subdir][config_name]["per_flow"][h_name] = {
                            "total": h_val["total"],
                            "stats": {f"{k[0]},{k[1]}": v for k, v in h_val["stats"].items()}
                        }
        json.dump(serialized, f, indent=2)
    print(f"Finished analysis. Output written to: {summary_json_path.relative_to(REPOSITORY_ROOT)}")

if __name__ == "__main__":
    main()
