#!/usr/bin/env python3
"""
802.11ax Packet Type Statistics and Airtime Analysis Script

This script automatically parses the PCAPs generated by the IEEE 802.11ax simulation
examples, calculates frame counts, percentages, size distributions (mean and standard
deviation in bytes), and estimated physical airtime occupancy percentages for each frame
type, and integrates the formatted markdown tables directly into the walkthrough.md of
each example directory.

Usage:
    python3 examples/ieee80211ax/analysis/analyze_pcap_types.py

Requirements:
    - Python 3.x
    - tshark (Wireshark command-line utility) in system PATH
    - Runs from the project root directory
"""

import os
import re
import glob
import json
import subprocess
import math
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import zlib
import colorsys

# Resolve project repository root (3 levels up from this file)
REPOSITORY_ROOT = Path(__file__).resolve().parents[3]

# Subdirectories and the specific configurations to analyze / run if PCAPs are missing
subdirs_configs = {
    "twt": ["Baseline", "IndividualUnannounced", "IndividualAnnounced", "Broadcast"],
    "mac_features/dynamic_fragmentation": ["DynamicFragmentation"],
    "mac_features/multi_tid_block_ack": ["MultiTidBlockAck", "UlMuMultiTidBlockAck", "UlSuMultiTidBlockAck"],
    "mac_features/operating_mode_indication": ["OperatingModeIndication"],
    "bss_coloring": ["BssColoringDisabled", "BssColoringEnabled", "ObssPdConservative", "ObssPdAggressive", "BssColoringCollision", "TwoNav"],
    "frequency_selective_channel": ["FlatChannelOFDMA", "TgaxModelBOFDMA"],
    "he_features": ["BccBaseline", "PreamblePuncturing"],
    "he_channel_widths": ["Width20MHz", "Width40MHz", "Width80MHz", "Width160MHz"],
    "multi_user/ndp_feedback": ["NdpFeedbackReport"],
    "multi_user/mu_mimo": ["DlMuMimo", "UlMuMimo"],
    "dl_ofdma": [
        "EqualSizedRUs_fBW", "EqualSizedRUs_fBW_ACVO", "EqualSizedRUs_fHoL", 
        "EqualSizedRUs_fHoL_ACVO", "SuEdcaBaseline", "EqualSizedRUs80MHz_fBW", 
        "EqualSizedRUs80MHz_fHoL", "SuEdcaBaseline80MHz", "BacklogBased", "HoLMinDelay", 
        "MultiTidBlockAck"
    ],
    "he_rate_adaptation": ["HeMinstrel", "FixedMcs", "HeMinstrelMobile"],
    "he_bsr": ["ImplicitBsr", "StaleBsr", "FullBsrAccounting"],
    "ul_ofdma": ["OperatingModeIndication", "UlMuMultiTidBlockAck", "UlSuMultiTidBlockAck"],
    "he_er_su": ["ErBss", "HeSu", "HeErSu"]
}

subtypes_mgmt = {
    0: "Association Request",
    1: "Association Response",
    2: "Reassociation Request",
    3: "Reassociation Response",
    4: "Probe Request",
    5: "Probe Response",
    8: "Beacon",
    9: "ATIM",
    10: "Disassociation",
    11: "Authentication",
    12: "Deauthentication",
    13: "Action",
    14: "Action No Ack",
}

subtypes_ctrl = {
    2: "Trigger",
    7: "Control Wrapper",
    8: "Block Ack Request (BAR)",
    9: "Block Ack (BA)",
    10: "PS-Poll",
    11: "RTS",
    12: "CTS",
    13: "Ack",
    14: "CF-End",
    15: "CF-End + CF-Ack",
}

subtypes_data = {
    0: "Data",
    4: "Null Function",
    8: "QoS Data",
    12: "QoS Null",
}

def unpack_key_to_name(key):
    fc_type = key[0]
    fc_subtype = key[1]
    if len(key) > 3:
        standard, mcs, bw, gi, nss, coding, is_ampdu, is_sounding = key[2:10]
        return get_packet_type_name(fc_type, fc_subtype, standard=standard, mcs=mcs, bw=bw, gi=gi, nss=nss, coding=coding, is_ampdu=is_ampdu, is_sounding=is_sounding)
    else:
        is_he_mu = key[2] if len(key) > 2 else False
        return get_packet_type_name(fc_type, fc_subtype, is_he_mu=is_he_mu)

def get_packet_type_name(fc_type, fc_subtype, fc_version=None, is_he_mu=False, standard=None, mcs=None, bw=None, gi=None, nss=None, coding=None, is_ampdu=False, is_sounding=False):
    suffix = ""
    if is_sounding:
        suffix += " [NDP Sounding]"
    elif standard and standard != "Legacy":
        parts = []
        if standard:
            parts.append(standard)
        if mcs and mcs != standard:
            parts.append(mcs)
        if bw:
            parts.append(bw)
        if gi:
            parts.append(f"GI {gi}")
        if nss and nss != "1":
            parts.append(f"NSS {nss}")
        if coding:
            parts.append(coding)
        if is_ampdu:
            parts.append("A-MPDU")
        suffix += " [" + ", ".join(parts) + "]"
    elif is_he_mu:
        suffix += " (HE-MU OFDMA)"

    if fc_type == "Aggregation Overhead":
        return "A-MPDU Delimiter / Aggregation Overhead" + suffix
    if fc_type == "HE TB feedback NDP":
        return "Control: HE TB feedback NDP" + suffix

    # Handle multiple values (e.g. from reassembled frames)
    version_str = fc_version.split(',')[0] if fc_version else ""
    type_str = fc_type.split(',')[0] if fc_type else ""
    subtype_str = fc_subtype.split(',')[0] if fc_subtype else ""
    
    try:
        v = int(version_str, 0) if version_str else 0
    except (ValueError, TypeError):
        v = 0

    if v > 0:
        return "A-MPDU Delimiter / Aggregation Overhead" + suffix

    try:
        t = int(type_str, 0)
        st = int(subtype_str, 0)
    except (ValueError, TypeError):
        return "Other/Malformed" + suffix
        
    if t == 0:
        return f"Management: {subtypes_mgmt.get(st, f'Subtype {st}')}" + suffix
    elif t == 1:
        return f"Control: {subtypes_ctrl.get(st, f'Subtype {st}')}" + suffix
    elif t == 2:
        return f"Data: {subtypes_data.get(st, f'Subtype {st}')}" + suffix
    else:
        return f"Unknown (Type {t}, Subtype {st})" + suffix

def decode_he(raw_d1, raw_d3, raw_d4, raw_d5):
    try:
        d1 = int(raw_d1, 16) if raw_d1 else 0
        d3 = int(raw_d3, 16) if raw_d3 else 0
        d4 = int(raw_d4, 16) if raw_d4 else 0
        d5 = int(raw_d5, 16) if raw_d5 else 0
    except ValueError:
        return "HE-SU", "HE-MCS 0", "20 MHz", "0.8 us", "1", "BCC"

    # PPDU Format
    fmt = d1 & 0x3
    if fmt == 0:
        standard = "HE-SU"
    elif fmt == 1:
        standard = "HE-ER-SU"
    elif fmt == 2:
        standard = "HE-MU"
    elif fmt == 3:
        standard = "HE-TB"
    else:
        standard = "HE"

    # MCS
    mcs_val = d5 & 0xF
    mcs = f"HE-MCS {mcs_val}"

    # NSS
    nss_val = ((d5 >> 4) & 0x7) + 1
    nss = f"{nss_val}"

    # Coding
    coding_val = (d5 >> 8) & 0x1
    coding = "LDPC" if coding_val == 1 else "BCC"

    # GI
    gi_val = d3 & 0x7
    if gi_val == 0:
        gi = "0.8 us"
    elif gi_val == 1:
        gi = "1.6 us"
    elif gi_val == 2:
        gi = "3.2 us"
    else:
        gi = "0.8 us"

    # BW
    bw_val = d4 & 0x7
    if bw_val == 0:
        bw = "20 MHz"
    elif bw_val == 1:
        bw = "40 MHz"
    elif bw_val == 2:
        bw = "80 MHz"
    elif bw_val == 3:
        bw = "160 MHz"
    else:
        bw = "20 MHz"

    return standard, mcs, bw, gi, nss, coding

def calculate_phy_rate(standard, mcs_str, bw_str, gi_str, nss_str):
    try:
        bw_mhz = 20
        if "160" in bw_str:
            bw_mhz = 160
        elif "80" in bw_str:
            bw_mhz = 80
        elif "40" in bw_str:
            bw_mhz = 40

        nss = 1
        if nss_str:
            try:
                nss = int(nss_str)
            except ValueError:
                pass

        if standard == "Legacy":
            rate_val = float(mcs_str.split()[0])
            return rate_val * 1e6

        mcs = 0
        if "MCS" in mcs_str:
            try:
                mcs = int(mcs_str.split()[-1])
            except ValueError:
                pass

        if standard == "HT":
            nsd = 108 if bw_mhz == 40 else 52
            duration = 3.6e-6 if "0.4" in gi_str else 4.0e-6
            base_mcs = mcs % 8
            nss = (mcs // 8) + 1
            mcs_bits = {0: 0.5, 1: 1.0, 2: 1.5, 3: 2.0, 4: 3.0, 5: 4.0, 6: 4.5, 7: 5.0}[base_mcs]
            return (nsd * nss * mcs_bits) / duration

        elif standard == "VHT":
            nsd_map = {20: 52, 40: 108, 80: 242, 160: 484}
            nsd = nsd_map.get(bw_mhz, 52)
            duration = 3.6e-6 if "0.4" in gi_str else 4.0e-6
            mcs_bits = {0: 0.5, 1: 1.0, 2: 1.5, 3: 2.0, 4: 3.0, 5: 4.0, 6: 4.5, 7: 5.0, 8: 6.0, 9: 6.6667}.get(mcs, 0.5)
            return (nsd * nss * mcs_bits) / duration

        elif "HE" in standard or standard == "EHT":
            nsd_map = {20: 234, 40: 468, 80: 980, 160: 1960}
            nsd = nsd_map.get(bw_mhz, 234)
            if "1.6" in gi_str:
                duration = 14.4e-6
            elif "3.2" in gi_str:
                duration = 16.0e-6
            else:
                duration = 13.6e-6
            mcs_bits = {0: 0.5, 1: 1.0, 2: 1.5, 3: 2.0, 4: 3.0, 5: 4.0, 6: 4.5, 7: 5.0, 8: 6.0, 9: 6.6667, 10: 7.5, 11: 8.3333}.get(mcs, 0.5)
            return (nsd * nss * mcs_bits) / duration

    except Exception:
        pass
    # Fallback to config name heuristics
    if "160mhz" in bw_str.lower():
        return 122.5e6
    elif "80mhz" in bw_str.lower():
        return 61.25e6
    elif "40mhz" in bw_str.lower():
        return 28.8e6
    else:
        return 14.625e6

def estimate_airtime(fc_type, fc_subtype, size, config_name, subdir, fc_version=None, standard="Legacy", data_rate=14.625e6, is_sounding=False):
    if fc_type == "Aggregation Overhead":
        return 20e-6 + (size * 8) / 24e6
    if fc_type == "HE TB feedback NDP" or is_sounding:
        return 72e-6

    # Handle multiple values
    type_str = fc_type.split(',')[0] if fc_type else ""
    subtype_str = fc_subtype.split(',')[0] if fc_subtype else ""

    try:
        t = int(type_str, 0)
        st = int(subtype_str, 0)
    except (ValueError, TypeError):
        return 20e-6 + (size * 8) / 6e6

    # Preamble duration based on standard
    if "HE" in standard or standard == "EHT":
        preamble = 124e-6
    elif standard == "VHT":
        preamble = 40e-6
    elif standard == "HT":
        preamble = 36e-6
    else:
        preamble = 20e-6

    if t == 0:  # Management
        return 20e-6 + (size * 8) / 6e6
    elif t == 1:  # Control
        return 20e-6 + (size * 8) / 24e6
    elif t == 2:  # Data
        return preamble + (size * 8) / data_rate
    else:
        return 20e-6 + (size * 8) / 6e6

def find_ini_file_for_config(subdir, config_name):
    def has_config(ini_path, cfg_name, visited=None):
        if visited is None:
            visited = set()
        ini_path = Path(ini_path).resolve()
        if ini_path in visited:
            return False
        visited.add(ini_path)
        if not ini_path.exists():
            return False
        try:
            with open(ini_path, "r") as f:
                content = f.read()
                if f"[Config {cfg_name}]" in content:
                    return True
                for line in content.splitlines():
                    line = line.strip()
                    if line.startswith("include "):
                        inc_file = line[len("include "):].strip()
                        inc_path = (ini_path.parent / inc_file).resolve()
                        if has_config(inc_path, cfg_name, visited):
                            return True
        except Exception:
            pass
        return False

    dir_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir
    ini_files = glob.glob(str(dir_path / "*.ini"))
    for ini in ini_files:
        if has_config(ini, config_name):
            return Path(ini)
    if ini_files:
        return Path(ini_files[0])
    return dir_path / "omnetpp.ini"

def get_sim_time_limit(subdir, config_name):
    ini_file = find_ini_file_for_config(subdir, config_name)
    cmd = [
        "bin/inet", "-e", "sim-time-limit", "-c", config_name, "-f", str(ini_file)
    ]
    try:
        proc = subprocess.run(cmd, cwd=str(REPOSITORY_ROOT), check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        for line in proc.stdout.splitlines():
            line = line.strip()
            if line.endswith('s'):
                val_str = line[:-1]
                try:
                    return float(val_str)
                except ValueError:
                    pass
    except Exception as e:
        print(f"Error querying sim-time-limit for {config_name} in {subdir}: {e}")
    
    try:
        with open(ini_file, "r") as f:
            content = f.read()
            match = re.search(r"sim-time-limit\s*=\s*([\d\.]+)\s*s", content)
            if match:
                return float(match.group(1))
    except Exception:
        pass
        
    return 2.0

def run_simulation(config_name, subdir):
    print(f"Generating PCAPs for {subdir} - {config_name}...")
    ini_file = find_ini_file_for_config(subdir, config_name)
    res_dir = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir / "results"
    res_dir.mkdir(parents=True, exist_ok=True)
    
    cmd = [
        "bin/inet", "-u", "Cmdenv", "-f", str(ini_file), "-c", config_name, "-r", "0",
        "--**.wlan[*].recordPcap=true",
        "--**.wlan[*].pcapRecorder[*].moduleNamePatterns=\"mac\"",
        "--**.wlan[*].pcapRecorder[*].verbose=false",
        "--**.checksumMode=\"computed\"", "--**.fcsMode=\"computed\"",
        f"--result-dir={res_dir}"
    ]
    try:
        subprocess.run(cmd, cwd=str(REPOSITORY_ROOT), check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print(f"Generated PCAPs successfully for {config_name}")
    except Exception as e:
        print(f"Simulation failed for {config_name}: {e}")

def get_config_pcap_stats(pcap_files, config_name, subdir, display_filter=None):
    total_sim_time = get_sim_time_limit(subdir, config_name)
    stats = {}
    total = 0
    total_airtime = 0.0
    
    fields = [
        "wlan.fc.version",                    # 0
        "wlan.fc.type",                       # 1
        "wlan.fc.subtype",                    # 2
        "frame.len",                          # 3
        "radiotap.length",                    # 4
        "radiotap.channel.freq",              # 5
        "radiotap.dbm_antsignal",             # 6
        "radiotap.txpower",                   # 7
        "radiotap.datarate",                  # 8
        "radiotap.present.mcs",               # 9
        "radiotap.mcs.index",                 # 10
        "radiotap.mcs.bw",                    # 11
        "radiotap.mcs.gi",                    # 12
        "radiotap.mcs.fec",                   # 13
        "radiotap.present.ampdu",             # 14
        "radiotap.ampdu.reference",           # 15
        "radiotap.ampdu.flags.last",          # 16
        "radiotap.present.vht",               # 17
        "radiotap.vht.mcs.0",                 # 18
        "radiotap.vht.nss.0",                 # 19
        "radiotap.vht.bw",                    # 20
        "radiotap.vht.gi",                    # 21
        "radiotap.vht.coding.0",              # 22
        "radiotap.present.he",                # 23
        "radiotap.present.he_mu",             # 24
        "radiotap.he.data_1.ppdu_format",     # 25
        "radiotap.he.data_3.data_mcs",        # 26
        "radiotap.he.data_3.coding",          # 27
        "radiotap.he.data_5.gi",              # 28
        "radiotap.he.data_6.nsts",            # 29
        "radiotap.present.0_length.psdu",     # 30
        "radiotap.present.word",              # 31
        "radiotap.he.data_3",                 # 32
        "radiotap.he.data_4",                 # 33
        "radiotap.he.data_5",                 # 34
    ]

    def get_field_val(parts, idx):
        if idx < len(parts) and parts[idx]:
            return parts[idx].split(',')[0].strip()
        return ""

    for pf in pcap_files:
        if not os.path.exists(pf):
            continue
        try:
            cmd = ["tshark", "-n", "-r", pf, "-T", "fields"]
            for f in fields:
                cmd.extend(["-e", f])
            if display_filter:
                cmd.extend(["-Y", display_filter])
            proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False)
            if proc.returncode != 0:
                print(f"Warning: tshark returned exit code {proc.returncode} for {pf}, but proceeding to parse output")
            for line in proc.stdout.splitlines():
                line = line.strip()
                if not line:
                    continue
                parts = line.split('\t')
                
                # If there are fewer than 4 fields, it lacks wlan fields (e.g. Ethernet frame)
                if len(parts) < 4:
                    continue
                
                fc_version = get_field_val(parts, 0)
                is_wlan_present = fc_version in ["0", "1", "2"]
                
                if not is_wlan_present:
                    fc_version = ""
                    fc_type = ""
                    fc_subtype = ""
                    size_str = parts[0] if len(parts) > 0 else ""
                    radiotap_len_str = parts[1] if len(parts) > 1 else ""
                    freq_str = parts[2] if len(parts) > 2 else ""
                    antsig_str = parts[3] if len(parts) > 3 else ""
                    txpower_str = ""
                    present_word_str = ""
                    is_ampdu = False
                    is_sounding = False
                    standard = "Legacy"
                    mcs = "Legacy"
                    bw = "20 MHz"
                    gi = "0.8 us"
                    nss = "1"
                    coding = ""
                else:
                    fc_type = get_field_val(parts, 1)
                    fc_subtype = get_field_val(parts, 2)
                    size_str = get_field_val(parts, 3)
                    radiotap_len_str = get_field_val(parts, 4)
                    freq_str = get_field_val(parts, 5)
                    antsig_str = get_field_val(parts, 6)
                    txpower_str = get_field_val(parts, 7)
                    present_word_str = get_field_val(parts, 31)
                    
                    is_sounding = get_field_val(parts, 30) in ("True", "1")
                    is_ampdu = get_field_val(parts, 14) in ("True", "1")
                    
                    is_eht = False
                    if present_word_str:
                        try:
                            words = [int(w, 16) for w in present_word_str.split(',')]
                            if len(words) > 1 and (words[1] & 0x00000008):
                                is_eht = True
                        except ValueError:
                            pass

                    if is_eht:
                        standard = "EHT"
                        mcs = "EHT"
                        bw = "20 MHz"
                        gi = "0.8 us"
                        nss = "1"
                        coding = ""
                    elif get_field_val(parts, 23) in ("True", "1"):
                        raw_d1 = get_field_val(parts, 25)
                        raw_d3 = get_field_val(parts, 32)
                        raw_d4 = get_field_val(parts, 33)
                        raw_d5 = get_field_val(parts, 34)
                        standard, mcs, bw, gi, nss, coding = decode_he(raw_d1, raw_d3, raw_d4, raw_d5)
                        if standard == "HE-SU" and get_field_val(parts, 24) in ("True", "1"):
                            standard = "HE-MU"
                    elif get_field_val(parts, 17) in ("True", "1"):
                        standard = "VHT"
                        vht_mcs_val = get_field_val(parts, 18)
                        mcs = f"VHT-MCS {vht_mcs_val}" if vht_mcs_val else "VHT"
                        vht_nss_val = get_field_val(parts, 19)
                        nss = vht_nss_val if vht_nss_val else "1"
                        
                        vht_bw_val = get_field_val(parts, 20)
                        if vht_bw_val == "0": bw = "20 MHz"
                        elif vht_bw_val == "1": bw = "40 MHz"
                        elif vht_bw_val == "4": bw = "80 MHz"
                        elif vht_bw_val == "11": bw = "160 MHz"
                        else: bw = "20 MHz"
                        
                        vht_gi_val = get_field_val(parts, 21)
                        gi = "0.4 us" if vht_gi_val == "1" else "0.8 us"
                        
                        vht_coding_val = get_field_val(parts, 22)
                        coding = "LDPC" if vht_coding_val == "1" else "BCC"
                    elif get_field_val(parts, 9) in ("True", "1"):
                        standard = "HT"
                        ht_mcs_val = get_field_val(parts, 10)
                        mcs = f"HT-MCS {ht_mcs_val}" if ht_mcs_val else "HT"
                        if ht_mcs_val:
                            try:
                                nss = str((int(ht_mcs_val) // 8) + 1)
                            except ValueError:
                                nss = "1"
                        else:
                            nss = "1"
                        
                        ht_bw_val = get_field_val(parts, 11)
                        bw = "40 MHz" if ht_bw_val == "1" else "20 MHz"
                        
                        ht_gi_val = get_field_val(parts, 12)
                        gi = "0.4 us" if ht_gi_val == "1" else "0.8 us"
                        
                        ht_fec_val = get_field_val(parts, 13)
                        coding = "LDPC" if ht_fec_val == "1" else "BCC"
                    else:
                        standard = "Legacy"
                        datarate_val = get_field_val(parts, 8)
                        mcs = f"{datarate_val} Mbps" if datarate_val else "Legacy"
                        bw = "20 MHz"
                        gi = "0.8 us"
                        nss = "1"
                        coding = ""
                
                try:
                    size = int(size_str)
                except ValueError:
                    size = 0
                
                if radiotap_len_str:
                    try:
                        size -= int(radiotap_len_str)
                    except ValueError:
                        pass
                size = max(0, size)
                
                try:
                    v = int(fc_version, 0) if fc_version else 0
                except (ValueError, TypeError):
                    v = 0
                
                if (not fc_type or fc_type == "") and (not fc_subtype or fc_subtype == ""):
                    if config_name in ["NdpFeedbackReport", "FeedbackUnderInterference"]:
                        key = ("HE TB feedback NDP", "", standard, mcs, bw, gi, nss, coding, is_ampdu, True)
                    else:
                        key = ("Aggregation Overhead", "", standard, mcs, bw, gi, nss, coding, is_ampdu, is_sounding)
                elif v > 0:
                    key = ("Aggregation Overhead", "", standard, mcs, bw, gi, nss, coding, is_ampdu, is_sounding)
                else:
                    key = (fc_type, fc_subtype, standard, mcs, bw, gi, nss, coding, is_ampdu, is_sounding)
                
                if key not in stats:
                    stats[key] = {
                        "sizes": [],
                        "airtimes": [],
                        "frequencies": [],
                        "signals": [],
                        "txpowers": []
                    }
                    
                data_rate = calculate_phy_rate(standard, mcs, bw, gi, nss)
                airtime = estimate_airtime(key[0], key[1], size, config_name, subdir, fc_version, standard, data_rate, is_sounding)
                stats[key]["sizes"].append(size)
                stats[key]["airtimes"].append(airtime)
                
                if freq_str:
                    try:
                        stats[key]["frequencies"].append(int(freq_str))
                    except ValueError:
                        pass
                if antsig_str:
                    try:
                        stats[key]["signals"].append(int(antsig_str))
                    except ValueError:
                        pass
                if txpower_str:
                    try:
                        stats[key]["txpowers"].append(int(txpower_str))
                    except ValueError:
                        pass
                
                total_airtime += airtime
                total += 1
        except Exception as e:
            print(f"Error reading {pf}: {e}")
            
    aggregated = {}
    for key, item in stats.items():
        sizes = item["sizes"]
        airtimes = item["airtimes"]
        freqs = item.get("frequencies", [])
        signals = item.get("signals", [])
        txpowers = item.get("txpowers", [])
        
        count = len(sizes)
        mean_size = sum(sizes) / count if count > 0 else 0
        variance = sum((x - mean_size) ** 2 for x in sizes) / count if count > 0 else 0
        std_size = math.sqrt(variance)
        
        mean_airtime = sum(airtimes) / count if count > 0 else 0
        var_airtime = sum((x - mean_airtime) ** 2 for x in airtimes) / count if count > 0 else 0
        std_airtime = math.sqrt(var_airtime)
        
        sum_airtime = sum(airtimes)
        airtime_pct = (sum_airtime / total_airtime) * 100 if total_airtime > 0 else 0.0
        airtime_sim_pct = (sum_airtime / total_sim_time) * 100 if total_sim_time > 0 else 0.0
        
        if freqs:
            unique_freqs = sorted(list(set(freqs)))
            freq_str = ", ".join(f"{f} MHz" for f in unique_freqs)
        else:
            freq_str = "-"
            
        if signals:
            mean_sig = sum(signals) / len(signals)
            sig_str = f"{mean_sig:.1f} dBm"
        else:
            sig_str = "-"
            
        if txpowers:
            mean_tx = sum(txpowers) / len(txpowers)
            tx_str = f"{mean_tx:.1f} dBm"
        else:
            tx_str = "-"
            
        aggregated[key] = {
            "count": count,
            "mean": mean_size,
            "std": std_size,
            "mean_duration": mean_airtime,
            "std_duration": std_airtime,
            "airtime_pct": airtime_pct,
            "airtime_sim_pct": airtime_sim_pct,
            "freq": freq_str,
            "rx_sig": sig_str,
            "tx_pwr": tx_str
        }
    return aggregated, total

def analyze_subdirectory(subdir, considered):
    dir_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir
    if not dir_path.exists():
        return None
        
    print(f"[{subdir}] Analyzing configs: {considered}")
    
    # Check if PCAPs exist for considered configs. If not, generate them!
    res_dir = dir_path / "results"
    for cfg in considered:
        wlan_pcaps = glob.glob(str(res_dir / f"{cfg}-*.pcap"))
        wlan_pcaps = [p for p in wlan_pcaps if ".wlan" in os.path.basename(p)]
        if not wlan_pcaps:
            run_simulation(cfg, subdir)
            
    # Gather PCAPs again
    pcap_files = []
    for root, _, files in os.walk(str(dir_path)):
        for f in files:
            if f.endswith(".pcap") or f.endswith(".pcapng"):
                pcap_files.append(os.path.join(root, f))
                
    config_pcaps = {}
    for pf in pcap_files:
        filename = os.path.basename(pf)
        if ".wlan" not in filename:
            continue
        
        match = re.match(r"^([^-]+)-#\d+", filename)
        if match:
            config_name = match.group(1)
        else:
            config_name = filename.split(".")[0]
            
        if config_name not in considered:
            continue
            
        if config_name not in config_pcaps:
            config_pcaps[config_name] = []
        config_pcaps[config_name].append(pf)
        
    config_results = {}
    for config_name, pcaps in config_pcaps.items():
        ap_pcaps = [p for p in pcaps if ".ap." in os.path.basename(p) or ".ap1." in os.path.basename(p) or ".ap2." in os.path.basename(p)]
        target_pcaps = ap_pcaps if ap_pcaps else pcaps
        
        print(f"[{subdir}] Analyzing config: {config_name} (Global) with pcaps: {[os.path.basename(p) for p in target_pcaps]}")
        stats, total = get_config_pcap_stats(target_pcaps, config_name, subdir)
        
        config_results[config_name] = {
            "global": {
                "stats": stats,
                "total": total,
                "used_ap_only": bool(ap_pcaps)
            }
        }
        
        # If asymmetric case in dl_ofdma, we also extract host specific traffic using display filters on the AP capture
        if subdir == "dl_ofdma" and config_name in ["BacklogBased", "HoLMinDelay"]:
            hosts_info = {
                "host[0]": "wlan.addr == 0a:aa:00:00:00:01",
                "host[1]": "wlan.addr == 0a:aa:00:00:00:02",
                "host[2]": "wlan.addr == 0a:aa:00:00:00:03"
            }
            
            # Read sca values for all hosts
            sca_file = dir_path / "results" / f"{config_name}-#0.sca"
            sca_data = {}
            if sca_file.exists():
                try:
                    with open(sca_file, "r") as f:
                        for line in f:
                            if "packetReceivedFromPeerUnicast" in line:
                                parts = line.split()
                                if len(parts) >= 4 and parts[0] == "scalar":
                                    module = parts[1]
                                    name = parts[2]
                                    val = float(parts[3])
                                    for h_idx in [0, 1, 2]:
                                        if f"host[{h_idx}]" in module:
                                            if h_idx not in sca_data:
                                                sca_data[h_idx] = {}
                                            if "count" in name:
                                                sca_data[h_idx]["count"] = int(val)
                                            elif "sum" in name:
                                                sca_data[h_idx]["sum"] = val
                except Exception as e:
                    print(f"Error parsing sca file {sca_file}: {e}")

            missing_host_counts = [h_idx for h_idx in [0, 1, 2]
                                   if sca_data.get(h_idx, {}).get("count", 0) <= 0]
            if missing_host_counts:
                print(
                    f"[{subdir}] Skipping unsupported per-flow tables for {config_name}: "
                    "HE MU payloads use a broadcast destination in this capture and "
                    f"recipient scalar counts are missing for hosts {missing_host_counts}"
                )
                continue

            config_results[config_name]["per_flow"] = {}

            for host_name, disp_filter in hosts_info.items():
                print(f"[{subdir}] Analyzing config: {config_name} ({host_name}) from AP capture using filter: {disp_filter}")
                h_stats, h_total = get_config_pcap_stats(target_pcaps, config_name, subdir, display_filter=disp_filter)
                
                # Correct the QoS Data count and sizes using sca data if available
                host_idx = int(host_name[-2])
                if host_idx in sca_data and "count" in sca_data[host_idx] and sca_data[host_idx]["count"] > 0:
                    count = sca_data[host_idx]["count"]
                    total_bytes = sca_data[host_idx].get("sum", 0)
                    mean_size = total_bytes / count if count > 0 else 0
                    
                    qos_key = ("2", "8") # QoS Data
                    # Subtract old QoS Data count from h_total
                    if qos_key in h_stats:
                        h_total -= len(h_stats[qos_key]["sizes"])
                    else:
                        h_stats[qos_key] = {"sizes": [], "airtimes": [], "frequencies": [], "signals": [], "txpowers": []}
                    
                    # Fill with new correct data
                    h_stats[qos_key]["sizes"] = [mean_size] * count
                    h_stats[qos_key]["airtimes"] = [estimate_airtime("2", "8", mean_size, config_name, subdir) for _ in range(count)]
                    h_total += count

                config_results[config_name]["per_flow"][host_name] = {
                    "stats": h_stats,
                    "total": h_total
                }
            
    return config_results

def make_table_md(stats, total):
    if total == 0:
        return "No packets captured.\n\n"
    md = []
    md.append("| Color | Frame Type & Subtype | Count | Percentage | Mean Size | Std Dev | Mean Duration | Std Dev Duration | Freq | Mean RX Sig | Mean TX Pwr | Air Time % | Air Time (Sim Time) % |\n")
    md.append("|:---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
    
    sorted_stats = sorted(stats.items(), key=lambda x: get_sort_key(unpack_key_to_name(x[0])))
    
    prev_category = None
    for key, stat in sorted_stats:
        name = unpack_key_to_name(key)
        
        # Determine category to insert horizontal line separator
        category = name.split(":")[0] if ":" in name else "Other"
        if prev_category is not None and category != prev_category:
            # Insert a separator row with horizontal lines in each cell
            md.append("| " + " | ".join(["<hr>"] * 13) + " |\n")
            
        prev_category = category
        
        color = get_packet_color(name)
        color_svg = f'<svg width="16" height="16"><rect width="16" height="16" rx="3" fill="{color}" /></svg>'
        
        pct = (stat["count"] / total) * 100
        mean_sz = f"{stat['mean']:.1f} B"
        std_sz = f"{stat['std']:.1f} B"
        mean_dur = f"{stat['mean_duration'] * 1e6:.1f} us"
        std_dur = f"{stat['std_duration'] * 1e6:.1f} us"
        freq_str = stat.get("freq", "-")
        rx_sig_str = stat.get("rx_sig", "-")
        tx_pwr_str = stat.get("tx_pwr", "-")
        air_pct = f"{stat['airtime_pct']:.2f}%"
        air_sim_pct = f"{stat['airtime_sim_pct']:.2f}%"
        md.append(f"| {color_svg} | {name} | {stat['count']} | {pct:.2f}% | {mean_sz} | {std_sz} | {mean_dur} | {std_dur} | {freq_str} | {rx_sig_str} | {tx_pwr_str} | {air_pct} | {air_sim_pct} |\n")
    return "".join(md)

ORDERED_BASE_TYPES = [
    # Data
    "Data: Data",
    "Data: QoS Data",
    "Data: QoS Null",
    # Control
    "Control: Trigger",
    "Control: PS-Poll",
    "Control: HE TB feedback NDP",
    "Control: Block Ack Request",
    "Control: Block Ack",
    "Control: Ack",
    # Management
    "Management: Beacon",
    "Management: Probe Request",
    "Management: Probe Response",
    "Management: Association Request",
    "Management: Association Response",
    "Management: Authentication",
    "Management: Action",
]

def get_base_type(pt):
    return pt.split(" [")[0].split(" (")[0]

def get_sort_key(pt):
    base = get_base_type(pt)
    if base in ORDERED_BASE_TYPES:
        return (ORDERED_BASE_TYPES.index(base), pt)
    else:
        return (len(ORDERED_BASE_TYPES), pt)

def get_packet_color(pt):
    base = get_base_type(pt)
    
    # Define base HSL values for each category
    # Hue: 0-360, Saturation: 0-100 (%), Lightness: 0-100 (%)
    if base == "Data: Data":  # Regular data (Light Green)
        h, s, l = 120, 65, 75
    elif base == "Data: QoS Data":  # QoS (Green)
        h, s, l = 120, 70, 45
    elif base == "Data: QoS Null":  # QoS Null (Dark Green)
        h, s, l = 120, 75, 22
    elif base == "Control: Ack":  # Ack (Blue)
        h, s, l = 210, 80, 60
    elif base == "Control: Block Ack Request":  # BAR (Brown)
        h, s, l = 25, 55, 42
    elif base == "Control: Block Ack":  # BA (Dark Blue)
        h, s, l = 225, 85, 35
    elif base == "Control: Trigger":  # Trigger (Orange)
        h, s, l = 35, 95, 50
    elif base == "Control: HE TB feedback NDP":  # Gold/Yellow
        h, s, l = 50, 95, 48
    elif base == "Control: PS-Poll":  # Light Blue/Steel Blue
        h, s, l = 195, 75, 65
    elif base == "Management: Action":  # Action (Red)
        h, s, l = 0, 85, 50
    elif base == "Management: Beacon":  # Beacon (Crimson/Dark Red)
        h, s, l = 350, 90, 32
    elif base == "Management: Authentication":  # Pink
        h, s, l = 330, 85, 65
    elif base == "Management: Association Request":  # Rose
        h, s, l = 310, 80, 55
    elif base == "Management: Association Response":  # Light Purple/Violet
        h, s, l = 290, 75, 60
    elif base == "Management: Probe Request":  # Salmon/Coral
        h, s, l = 15, 85, 65
    elif base == "Management: Probe Response":  # Light Salmon
        h, s, l = 15, 85, 75
    else:
        # Unknown: use a default hashed color
        val = zlib.adler32(pt.encode('utf-8'))
        h = val % 360
        s = 60
        l = 50
        r, g, b = colorsys.hls_to_rgb(h / 360.0, l / 100.0, s / 100.0)
        return matplotlib.colors.to_hex((r, g, b))

    # Perturb HSL based on the suffix (to distinguish subtypes visually)
    suffix = pt[len(base):]
    if suffix:
        val = zlib.adler32(suffix.encode('utf-8'))
        # Perturb Hue by +/- 8 degrees
        h_offset = (val % 17) - 8
        h = (h + h_offset) % 360
        
        # Perturb Saturation by +/- 10%, keeping within [10, 100]
        s_offset = ((val >> 4) % 21) - 10
        s = max(10, min(100, s + s_offset))
        
        # Perturb Lightness by +/- 8%, keeping within [10, 90]
        l_offset = ((val >> 8) % 17) - 8
        l = max(10, min(90, l + l_offset))
        
    r, g, b = colorsys.hls_to_rgb(h / 360.0, l / 100.0, s / 100.0)
    return matplotlib.colors.to_hex((r, g, b))

def generate_stacked_bar_plot(config_results, subdir, color_map):
    # Filter configs that have global stats
    valid_configs = []
    for cfg_name in sorted(config_results.keys()):
        res = config_results[cfg_name]
        if "global" in res and res["global"]["total"] > 0:
            valid_configs.append(cfg_name)
            
    if not valid_configs:
        return
        
    # Get union of all packet type names
    packet_types = set()
    for cfg in valid_configs:
        stats = config_results[cfg]["global"]["stats"]
        for key in stats.keys():
            name = unpack_key_to_name(key)
            packet_types.add(name)
            
    packet_types = sorted(list(packet_types), key=get_sort_key)
    
    # Prepare data for plotting
    num_configs = len(valid_configs)
    count_data = {pt: np.zeros(num_configs) for pt in packet_types}
    airtime_data = {pt: np.zeros(num_configs) for pt in packet_types}
    
    for idx, cfg in enumerate(valid_configs):
        global_res = config_results[cfg]["global"]
        total = global_res["total"]
        stats = global_res["stats"]
        
        for key, stat in stats.items():
            name = unpack_key_to_name(key)
            pct = (stat["count"] / total) * 100
            count_data[name][idx] = pct
            airtime_data[name][idx] = stat["airtime_pct"]
            
    # Set up matplotlib style for a clean, premium look
    plt.rcParams['font.sans-serif'] = 'DejaVu Sans'
    plt.rcParams['font.family'] = 'sans-serif'
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 8.2))
    
    y = np.arange(num_configs)
    height = 0.45
    
    # Helper to format axes
    def style_axis(ax, title):
        ax.set_title(title, fontsize=14, pad=15, weight='bold', color='#2c3e50')
        ax.set_xlabel("Percentage (%)", fontsize=12, labelpad=10, color='#2c3e50')
        ax.set_yticks(y)
        ax.set_yticklabels(valid_configs, fontsize=10, color='#2c3e50')
        ax.set_xlim(0, 105)
        ax.grid(axis='x', linestyle='--', alpha=0.5, color='#bdc3c7')
        ax.set_axisbelow(True)
        ax.invert_yaxis()  # Keep configuration list top-to-bottom
        # Remove top and right spines
        for spine in ['top', 'right']:
            ax.spines[spine].set_visible(False)
        ax.spines['left'].set_color('#bdc3c7')
        ax.spines['bottom'].set_color('#bdc3c7')
        
    # Plot Count Percentages
    bottom_count = np.zeros(num_configs)
    for pt in packet_types:
        ax1.barh(y, count_data[pt], height, left=bottom_count, label=pt, color=color_map[pt], edgecolor='white', linewidth=0.5)
        bottom_count += count_data[pt]
    style_axis(ax1, "Packet Count Distribution (%)")
    
    # Plot Air Time Percentages
    bottom_air = np.zeros(num_configs)
    for pt in packet_types:
        ax2.barh(y, airtime_data[pt], height, left=bottom_air, label=pt, color=color_map[pt], edgecolor='white', linewidth=0.5)
        bottom_air += airtime_data[pt]
    style_axis(ax2, "Airtime Distribution (%)")
    
    # Common Legend below the plots
    handles, labels = ax1.get_legend_handles_labels()
    fig.legend(handles, labels, loc='upper center', bbox_to_anchor=(0.5, 0.23), ncol=2, fontsize=9.5, frameon=True, facecolor='#f8f9fa', edgecolor='#e2e8f0')
    
    plt.tight_layout(rect=[0.02, 0.27, 0.98, 0.95])
    
    # Save path
    plot_dir = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir
    plot_path = plot_dir / "packet_statistics.png"
    plt.savefig(str(plot_path), dpi=150, bbox_inches='tight')
    plt.close()

def generate_markdown_tables(config_results, subdir):
    if not config_results:
        return ""
    
    md = []
    md.append("## 802.11 Packet Type Statistics\n")
    md.append("![802.11 Packet Type Statistics](packet_statistics.png)\n\n")
    md.append("This section provides a statistical overview of the 802.11 frames transmitted over the wireless medium during the simulation. ")
    
    ap_used = all(res["global"]["used_ap_only"] for res in config_results.values() if "global" in res)
    if ap_used:
        md.append("The packet counts were gathered from the Access Point's wireless interface (`ap.wlan[0]`), which captures all uplink, downlink, and management traffic in the BSS without duplication.\n\n")
    else:
        md.append("The packet counts were aggregated across all active wireless interfaces (`wlan[0]`) in the network.\n\n")

    md.append(
        "> **HE capture metadata caveat:** The current INET `PcapRecorder` uses a "
        "repository-specific packing for HE radiotap metadata. TShark can consequently "
        "decode SU transmissions as HE ER SU and downlink HE MU transmissions as HE TB. "
        "Frame type, subtype, count, and size remain useful, but the HE PPDU-format, MCS, "
        "bandwidth, GI, NSS, and coding suffixes—and the airtime estimates derived from "
        "them—are diagnostic only and are not standards-conformance evidence.\n\n"
    )
        
    md.append("Two airtime occupancy percentages are provided:\n")
    md.append("- **Air Time %**: This frame type's share of the sum of all estimated frame airtimes.\n")
    md.append("- **Air Time (Sim Time) %**: The sum of this frame type's estimated airtimes divided by the simulation time limit. Concurrent transmissions from multiple capture points are counted separately, so this value can exceed 100%; it is not the union of busy channel time.\n\n")
        
    for config_name, res in sorted(config_results.items()):
        global_res = res.get("global")
        if not global_res or global_res["total"] == 0:
            continue
            
        md.append(f"### Configuration: `{config_name}`\n")
        md.append(f"Total over-the-air packets captured (Global BSS/AP): **{global_res['total']}**\n\n")
        md.append(make_table_md(global_res["stats"], global_res["total"]))
        md.append("\n")
        
        if "per_flow" in res:
            md.append(f"#### Per-Flow Traffic Statistics for `{config_name}`\n\n")
            
            flows_desc = {
                "host[0]": "Heavy Flow (destined to `host[0]`, offered load: 80 Mbps, size: 1000 B)",
                "host[1]": "Medium Flow (destined to `host[1]`, offered load: 8 Mbps, size: 400 B)",
                "host[2]": "Light Flow (destined to `host[2]`, offered load: 0.8 Mbps, size: 100 B)"
            }
            
            for host_name, flow_res in sorted(res["per_flow"].items()):
                md.append(f"##### {flows_desc.get(host_name, host_name)}\n")
                md.append(f"Total packets captured for flow: **{flow_res['total']}**\n\n")
                md.append(make_table_md(flow_res["stats"], flow_res["total"]))
                md.append("\n")
        
    md.append("### Analysis of Packet Distribution\n")
    
    analysis_text = ""
    if "twt" in subdir:
        analysis_text = (
            "Only `IndividualAnnounced` contains the large **PS-Poll** population. This is consistent with the announced-TWT procedure: "
            "the requester signals that it is awake with PS-Poll or an APSD trigger before the responder sends a non-Trigger frame "
            "(IEEE Std 802.11-2024, Table 9-347 and Clause 10.46). Unannounced TWT does not require that presence signal. "
            "The QoS Data totals are transmitted MPDU observations, not delivered application-packet counts; aggregation and repeated sequence numbers "
            "can make them much larger than the workload. Validate TWT delivery with sink scalars and energy with the recorded radio-power vectors."
        )
    elif "ul_ofdma" in subdir:
        analysis_text = (
            "The UL-MU configuration contains repeated **Trigger** frames followed by the solicited station transmissions and AP **Block Ack** responses, "
            "which is the expected HE UL-MU exchange structure (IEEE Std 802.11-2024, Clause 26.5.2 and Annex G.5). "
            "The operating-mode and UL-SU configurations are not expected to have the same Trigger population. Frame-subtype counts alone do not prove "
            "the RU assignments, HE TB format, Multi-STA Block Ack contents, or OM Control value; inspect the corresponding fields or simulator telemetry."
        )
    elif "dl_ofdma" in subdir:
        analysis_text = (
            "The scheduled downlink configurations show the expected repeating structure of downlink **QoS Data**, a **Trigger** used for the MU-BAR exchange, "
            "and multiple **Block Ack** responses. This matches the HE DL-MU acknowledgment sequence described by IEEE Std 802.11-2024 Clauses 26.5.1 and 26.5.2.3.3. "
            "Because the current radiotap metadata cannot reliably distinguish HE MU from HE TB, the frame sequence and scheduler telemetry—not the displayed PPDU suffix—are the usable evidence. "
            "**Per-flow limitation:** scheduled HE-MU payloads in these PCAPs use a broadcast destination address, so `wlan.addr` filters cannot attribute them to a user. "
            "The script now omits the asymmetric per-flow tables when matching recipient scalar counts are unavailable. Scheduler priorities and satisfaction must be "
            "measured from per-user scheduler/application results; IEEE 802.11 does not mandate the implementation's backlog or head-of-line scheduling policy."
        )
    elif "bss_coloring" in subdir:
        analysis_text = (
            "**Unexpected/no separation:** `BssColoringDisabled`, `BssColoringEnabled`, `ObssPdConservative`, `ObssPdAggressive`, and `BssColoringCollision` "
            "have identical frame counts and distributions in this run. IEEE Std 802.11-2024 Clause 26.10 permits eligible inter-BSS reuse after OBSS/PD "
            "classification; it does not guarantee a throughput improvement, and a more permissive threshold can increase interference. The identical result "
            "therefore does not violate the standard, but it means this bounded scalar-medium workload provides no evidence that coloring or the threshold sweep "
            "changed protocol behavior. The current model also omits dynamic OBSS/PD adaptation and the associated transmit-power-control adjustment."
        )
    elif "dynamic_fragmentation" in subdir:
        analysis_text = (
            "IEEE Std 802.11-2024 Clause 26.3 gates dynamic fragmentation on negotiated peer capability; it does not require fragment size to adapt to channel conditions. "
            "In this implementation the dynamic and static policies use the same 500-byte sizing policy after the capability gate, so their detailed result-analysis "
            "traces are expected to overlap. This packet table contains only `DynamicFragmentation`; it cannot establish a higher fragment count without the static "
            "and unfragmented controls, nor can Block Ack subtype counts alone establish the fragment bitmap."
        )
    elif "he_er_su" in subdir:
        analysis_text = (
            "**No range separation in this run:** `HeSu` and `HeErSu` have nearly identical QoS Data/Ack counts, so these packet statistics do not show HE-SU "
            "failing while HE-ER-SU succeeds. That is compatible with the standard: HE ER SU supplies a more robust format, but does not guarantee a gain on every "
            "channel. IEEE Std 802.11-2024 Clause 27.3.7 restricts HE ER SU to a single 242-tone or 106-tone RU and MCS 0–2 (242-tone) or MCS 0 (106-tone); "
            "DCM is optional. A coverage claim needs a controlled PER/delivery sweep, and the current malformed radiotap format field cannot prove ER-SU selection."
        )
    elif "he_rate_adaptation" in subdir:
        analysis_text = (
            "IEEE 802.11 constrains negotiated HE modes but does not mandate a Minstrel algorithm. These packet counts therefore cannot establish adaptation, "
            "and a control/data ratio is not reliable evidence of retransmission or probing. Use the aligned selected-MCS/NSS, EWMA probability, transmission-outcome, "
            "and retry vectors documented above. INET's HE Minstrel remains a simplified implementation without scheduler-context or localized-fading adaptation."
        )
    elif "he_channel_widths" in subdir:
        analysis_text = (
            "IEEE Std 802.11-2024 Table 27-1 defines 20, 40, 80, and 160 MHz HE channel-width encodings, but the standard does not require packet count or throughput "
            "to scale linearly with width. The run-0 frame totals here are non-monotonic because aggregation, RU scheduling, and fixed overhead change the number of "
            "transmitted frames. The five-run sink goodput and delay analysis above is the appropriate capacity comparison; the radiotap bandwidth suffix is not."
        )
    elif "ndp_feedback" in subdir:
        analysis_text = (
            "The capture contains both **Trigger** frames and zero-length HE TB feedback NDP observations, consistent with the NDP Feedback Report Poll exchange "
            "defined by IEEE Std 802.11-2024 Clause 26.5.7 and Annex G.5. One NFRP Trigger can allocate multiple feedback resources, so the counts need not be one-to-one. "
            "The generic Control-subtype label does not by itself prove Trigger Type 7; verify the Trigger field or simulator NFRP telemetry when conformance detail matters."
        )
    elif "multi_tid_block_ack" in subdir:
        analysis_text = (
            "BAR and Block Ack subtype counts show acknowledgment exchanges, but they do not identify the BA Control variant or its per-AID/TID entries. "
            "IEEE Std 802.11-2024 Clauses 9.3.1.8.6 and 10.25.5 require those contents to distinguish Multi-STA and Multi-TID operation. Treat this table as an exchange count; "
            "use decoded BA fields or simulator telemetry to prove that multiple TIDs were acknowledged."
        )
    elif "operating_mode_indication" in subdir:
        analysis_text = (
            "The data and acknowledgment counts show traffic before and after the configured operating-mode change, but frame subtype statistics cannot expose the "
            "Operating Mode Indication element or OM Control subfield. Standard behavior must be checked from those fields and the receiver's applied channel-width/NSS state, "
            "not inferred from the packet total."
        )
    elif "mu_mimo" in subdir:
        analysis_text = (
            "Packet totals alone do not establish MU-MIMO. IEEE Std 802.11-2024 Clause 27.3.2.5 identifies each HE-MU user and its spatial streams; the direct evidence is "
            "multiple users in one PPDU with compatible, non-overlapping stream allocations. Use the RU/NSS allocation telemetry and five-run comparison documented above, "
            "because the current radiotap suffix cannot reliably identify the PPDU format."
        )
    elif "he_bsr" in subdir:
        analysis_text = (
            "The scheduled conditions contain the expected Trigger/response activity, but a BSR is an A-Control scheduling input rather than a frame subtype. "
            "IEEE Std 802.11-2024 Clause 26.5.5 requires the report contents and capability conditions; use the AP-reported and scheduled-backlog telemetry documented above. "
            "QoS Data counts are not evidence that a BSR was fresh or that the reported bytes were delivered."
        )
    elif "he_features" in subdir:
        analysis_text = (
            "`BccBaseline` and `PreamblePuncturing` have identical frame counts in this run. That is not a standards violation and does not mean the PHY configuration was identical: "
            "preamble puncturing changes the usable subchannels/RU placement, while a fully served offered load can leave packet totals unchanged. Validate the mask and puncture-aware "
            "RU allocation with the vectors documented above; the current PCAP metadata cannot prove them."
        )
    elif "frequency_selective_channel" in subdir:
        analysis_text = (
            "The different frame mixtures show that the two configured access paths executed different exchanges, but aggregate subtype counts cannot validate a frequency-selective "
            "channel or per-RU isolation. IEEE HE DL-MU behavior must be established with RU allocation and per-RU reception/SNIR outcomes together with sink delivery; the channel model "
            "is an implementation choice rather than an IEEE-mandated propagation model."
        )
    else:
        analysis_text = (
            "Across these configurations, **QoS Data** frames constitute the primary payload delivery mechanism, "
            "while **Block Ack (BA)** and **Block Ack Request (BAR)** control frames ensure reliable transport via the MAC-level acknowledgment protocol. "
            "Management frames, specifically **Beacons**, are transmitted periodically by the Access Point to maintain BSS time synchronization "
            "and broadcast network capabilities. The ratio of control/management overhead to actual data frames indicates the relative MAC efficiency "
            "of the chosen configurations."
        )
        
    md.append(analysis_text + "\n")
    return "".join(md)

def update_walkthrough_file(subdir, md_content):
    walkthrough_path = REPOSITORY_ROOT / "examples" / "ieee80211ax" / subdir / "walkthrough.md"
    if not walkthrough_path.exists():
        print(f"Walkthrough file not found: {walkthrough_path}")
        return
        
    with open(walkthrough_path, "r") as f:
        content = f.read()
        
    section_header = "## 802.11 Packet Type Statistics"
    if section_header in content:
        pattern = re.compile(rf"{section_header}.*", re.DOTALL)
        new_content = pattern.sub(md_content, content)
    else:
        new_content = content.rstrip() + "\n\n" + md_content
        
    with open(str(walkthrough_path), "w") as f:
        f.write(new_content)
    print(f"Updated: {walkthrough_path.relative_to(REPOSITORY_ROOT)}")

def main():
    all_results = {}
    for subdir, considered in subdirs_configs.items():
        res = analyze_subdirectory(subdir, considered)
        if res:
            all_results[subdir] = res

    # Gather the union of all packet types across all results to use consistent colors
    global_packet_types = set()
    for subdir, subdir_res in all_results.items():
        for config_name, res in subdir_res.items():
            if "global" in res:
                stats = res["global"]["stats"]
                for key in stats.keys():
                    name = unpack_key_to_name(key)
                    global_packet_types.add(name)
                    
    global_packet_types = sorted(list(global_packet_types))
    
    # Assign a permanent color to each global packet type using HSL-based mapping
    global_color_map = {pt: get_packet_color(pt) for pt in global_packet_types}

    for subdir, res in all_results.items():
        generate_stacked_bar_plot(res, subdir, global_color_map)
        md_table = generate_markdown_tables(res, subdir)
        if md_table:
            update_walkthrough_file(subdir, md_table)

    summary_json_path = REPOSITORY_ROOT / "examples" / "ieee80211ax/analysis/summary_results_pcap.json"
    with summary_json_path.open("w") as f:
        serialized = {}
        for subdir, subdir_res in all_results.items():
            serialized[subdir] = {}
            for config_name, res in subdir_res.items():
                serialized[subdir][config_name] = {}
                if "global" in res:
                    g = res["global"]
                    serialized[subdir][config_name]["global"] = {
                        "total": g["total"],
                        "used_ap_only": g["used_ap_only"],
                        "stats": {",".join(str(x) for x in k): v for k, v in g["stats"].items()}
                    }
                if "per_flow" in res:
                    serialized[subdir][config_name]["per_flow"] = {}
                    for h_name, h_val in res["per_flow"].items():
                        serialized[subdir][config_name]["per_flow"][h_name] = {
                            "total": h_val["total"],
                            "stats": {",".join(str(x) for x in k): v for k, v in h_val["stats"].items()}
                        }
        json.dump(serialized, f, indent=2)
    print(f"Finished analysis. Output written to: {summary_json_path.relative_to(REPOSITORY_ROOT)}")

if __name__ == "__main__":
    main()
